"""
Bridge Safety System
=====================

Production-grade circuit breakers, anomaly detection, rate-limit
monitoring, and validator health tracking for the Rings ↔ Ethereum
bridge.

Components
~~~~~~~~~~

- :class:`CircuitBreaker` — configurable CLOSED → OPEN → HALF_OPEN
  state machine with sliding-window error rate and consecutive-failure
  thresholds.
- :class:`AnomalyDetector` — EWMA-based statistical anomaly detection
  for deposit/withdrawal volume, frequency, and value outliers.
- :class:`RateLimitMonitor` — tracks daily limit utilisation and
  predicts exhaustion.
- :class:`ValidatorHealthMonitor` — heartbeat liveness and attestation
  success rate tracking.
- :class:`BridgeSafetyManager` — orchestrates all safety sub-systems
  and can auto-pause the bridge contract on critical alerts.

No external ML dependencies — all anomaly detection uses exponentially
weighted moving averages and z-score thresholds (pure statistics).
"""

from __future__ import annotations

import logging
import math
import time
from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Deque, Dict, List, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Alert types
# ---------------------------------------------------------------------------


class AlertSeverity(Enum):
    """Severity levels for safety alerts."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    EMERGENCY = "emergency"


@dataclass
class SafetyAlert:
    """An alert generated by the monitoring system.

    Attributes
    ----------
    timestamp : float
        Unix timestamp when the alert was created.
    severity : AlertSeverity
        How severe the condition is.
    source : str
        Which monitor generated this alert (e.g. ``"circuit_breaker"``).
    message : str
        Human-readable description.
    metrics : dict
        Any numeric context (e.g. z-score, error rate).
    acknowledged : bool
        Whether an operator has ack'd this alert.
    """

    timestamp: float
    severity: AlertSeverity
    source: str
    message: str
    metrics: dict = field(default_factory=dict)
    acknowledged: bool = False


# ---------------------------------------------------------------------------
# CircuitBreaker
# ---------------------------------------------------------------------------


class CircuitBreaker:
    """Production circuit breaker with configurable thresholds.

    States: CLOSED (normal) → OPEN (tripped) → HALF_OPEN (testing recovery)

    Trips on:
    - Consecutive failure count exceeding *failure_threshold*.
    - Error rate exceeding *error_rate_threshold* in a sliding window
      of *window_size* results.
    - Manual :meth:`trip` call.

    Recovery:
    - After *cooldown_seconds*, transitions to HALF_OPEN.
    - In HALF_OPEN, the next :meth:`record_success` → CLOSED.
    - In HALF_OPEN, the next :meth:`record_failure` → OPEN (resets
      cooldown timer).
    """

    class State(Enum):
        CLOSED = "closed"
        OPEN = "open"
        HALF_OPEN = "half_open"

    def __init__(
        self,
        name: str,
        failure_threshold: int = 5,
        error_rate_threshold: float = 0.5,
        window_size: int = 20,
        cooldown_seconds: float = 60.0,
        on_trip: Optional[Callable] = None,
        on_reset: Optional[Callable] = None,
    ) -> None:
        self.name = name
        self.failure_threshold = failure_threshold
        self.error_rate_threshold = error_rate_threshold
        self.window_size = window_size
        self.cooldown_seconds = cooldown_seconds
        self.on_trip = on_trip
        self.on_reset = on_reset

        self.state = self.State.CLOSED
        self._consecutive_failures: int = 0
        self._results: Deque[bool] = deque(maxlen=window_size)
        self._last_failure_time: float = 0.0
        self._trip_count: int = 0

    # ── Recording ────────────────────────────────────────────────────────

    def record_success(self) -> None:
        """Record a successful operation.

        If the breaker is in HALF_OPEN, this resets it to CLOSED.
        """
        self._results.append(True)
        self._consecutive_failures = 0

        if self.state == self.State.HALF_OPEN:
            self._do_reset()

    def record_failure(self) -> None:
        """Record a failed operation.  May trip the breaker."""
        self._results.append(False)
        self._consecutive_failures += 1
        self._last_failure_time = time.time()

        if self.state == self.State.HALF_OPEN:
            # Probe failed — back to OPEN
            self._do_trip("half_open probe failed")
            return

        if self.state == self.State.CLOSED:
            # Check consecutive failures
            if self._consecutive_failures >= self.failure_threshold:
                self._do_trip(
                    f"consecutive failures ({self._consecutive_failures}) "
                    f">= threshold ({self.failure_threshold})"
                )
                return

            # Check sliding-window error rate
            if len(self._results) >= self.failure_threshold and self.error_rate > self.error_rate_threshold:
                self._do_trip(
                    f"error rate ({self.error_rate:.2%}) "
                    f"> threshold ({self.error_rate_threshold:.2%})"
                )

    # ── Availability ─────────────────────────────────────────────────────

    def is_available(self) -> bool:
        """Check whether operations should be allowed through.

        Returns ``True`` for CLOSED and HALF_OPEN states.  For OPEN,
        checks whether the cooldown has elapsed and auto-transitions to
        HALF_OPEN if so.
        """
        if self.state == self.State.CLOSED:
            return True

        if self.state == self.State.HALF_OPEN:
            return True

        # OPEN — check cooldown
        elapsed = time.time() - self._last_failure_time
        if elapsed >= self.cooldown_seconds:
            self.state = self.State.HALF_OPEN
            logger.info(
                "CircuitBreaker[%s]: OPEN → HALF_OPEN after %.1fs cooldown",
                self.name, elapsed,
            )
            return True

        return False

    # ── Manual controls ──────────────────────────────────────────────────

    def trip(self, reason: str = "manual") -> None:
        """Manually trip the breaker to OPEN state."""
        self._do_trip(reason)

    def reset(self) -> None:
        """Manually reset the breaker to CLOSED state."""
        self._do_reset()

    # ── Properties ───────────────────────────────────────────────────────

    @property
    def error_rate(self) -> float:
        """Current error rate in the sliding window (0.0–1.0)."""
        if not self._results:
            return 0.0
        failures = sum(1 for r in self._results if not r)
        return failures / len(self._results)

    @property
    def stats(self) -> dict:
        """Current breaker statistics."""
        return {
            "name": self.name,
            "state": self.state.value,
            "consecutive_failures": self._consecutive_failures,
            "error_rate": round(self.error_rate, 4),
            "window_size": len(self._results),
            "trip_count": self._trip_count,
            "last_failure_time": self._last_failure_time,
            "cooldown_seconds": self.cooldown_seconds,
        }

    # ── Internals ────────────────────────────────────────────────────────

    def _do_trip(self, reason: str) -> None:
        """Transition to OPEN and fire the on_trip callback."""
        prev = self.state
        self.state = self.State.OPEN
        self._trip_count += 1
        self._last_failure_time = time.time()
        logger.warning(
            "CircuitBreaker[%s]: %s → OPEN (reason: %s, trip #%d)",
            self.name, prev.value, reason, self._trip_count,
        )
        if self.on_trip is not None:
            try:
                self.on_trip(self.name, reason)
            except Exception:
                logger.exception("on_trip callback failed for %s", self.name)

    def _do_reset(self) -> None:
        """Transition to CLOSED and fire the on_reset callback."""
        prev = self.state
        self.state = self.State.CLOSED
        self._consecutive_failures = 0
        logger.info(
            "CircuitBreaker[%s]: %s → CLOSED", self.name, prev.value,
        )
        if self.on_reset is not None:
            try:
                self.on_reset(self.name)
            except Exception:
                logger.exception("on_reset callback failed for %s", self.name)

    def __repr__(self) -> str:
        return (
            f"CircuitBreaker({self.name!r}, state={self.state.value}, "
            f"errors={self.error_rate:.2%}, trips={self._trip_count})"
        )


# ---------------------------------------------------------------------------
# AnomalyDetector
# ---------------------------------------------------------------------------


class AnomalyDetector:
    """Detects anomalous bridge activity using statistical methods.

    Monitors:

    1. **Volume anomalies** — sudden spikes in deposit/withdrawal
       amounts that are statistical outliers.
    2. **Frequency anomalies** — unusually short inter-transaction
       intervals.
    3. **Failed-attempt patterns** — bursts of failures suggesting an
       attack.

    Uses exponentially weighted moving average (EWMA) and standard
    deviation for anomaly detection.  No ML dependencies — pure
    statistics.

    Parameters
    ----------
    volume_window : int
        Rolling window size for amount history.
    z_score_threshold : float
        Number of standard deviations for an outlier.
    ewma_alpha : float
        Smoothing factor for EWMA (0 < α ≤ 1).
    min_samples : int
        Minimum number of observations before alerting.
    """

    def __init__(
        self,
        volume_window: int = 100,
        z_score_threshold: float = 3.0,
        ewma_alpha: float = 0.1,
        min_samples: int = 10,
    ) -> None:
        self.volume_window = volume_window
        self.z_score_threshold = z_score_threshold
        self.ewma_alpha = ewma_alpha
        self.min_samples = min_samples

        # Amount history
        self._deposit_amounts: Deque[float] = deque(maxlen=volume_window)
        self._withdrawal_amounts: Deque[float] = deque(maxlen=volume_window)

        # Frequency tracking (deposit intervals)
        self._deposit_intervals: Deque[float] = deque(maxlen=volume_window)
        self._last_deposit_time: float = 0.0

        # EWMA state for deposits
        self._ewma_deposit: float = 0.0
        self._ewma_variance: float = 0.0
        self._deposit_count: int = 0

        # EWMA state for withdrawals
        self._ewma_withdrawal: float = 0.0
        self._ewma_withdrawal_variance: float = 0.0
        self._withdrawal_count: int = 0

        # EWMA state for deposit intervals
        self._ewma_interval: float = 0.0
        self._ewma_interval_variance: float = 0.0

        # Failed attempt tracking
        self._recent_failures: Deque[float] = deque(maxlen=volume_window)
        self._failure_burst_threshold: int = 5  # failures in 60s

        # All generated alerts
        self._alerts: List[SafetyAlert] = []

    # ── Public API ───────────────────────────────────────────────────────

    def observe_deposit(
        self,
        amount: int,
        sender: str,
        timestamp: Optional[float] = None,
    ) -> Optional[SafetyAlert]:
        """Record a deposit and check for anomalies.

        Parameters
        ----------
        amount : int
            Deposit amount in wei.
        sender : str
            Sender Ethereum address.
        timestamp : float, optional
            Observation time (defaults to ``time.time()``).

        Returns
        -------
        SafetyAlert or None
            An alert if the deposit is anomalous.
        """
        ts = timestamp if timestamp is not None else time.time()
        amt = float(amount)

        # Track frequency (check BEFORE updating EWMA)
        interval: Optional[float] = None
        if self._last_deposit_time > 0:
            interval = ts - self._last_deposit_time
        self._last_deposit_time = ts

        # Snapshot EWMA state BEFORE updating (so the outlier doesn't
        # pollute the baseline we compare against)
        prev_mean = self._ewma_deposit
        prev_var = self._ewma_variance
        prev_count = self._deposit_count

        # Now update tracking
        self._deposit_amounts.append(amt)
        self._deposit_count += 1
        self._update_ewma_deposit(amt)

        if interval is not None:
            self._deposit_intervals.append(interval)
            # Snapshot interval EWMA before update
            prev_interval_mean = self._ewma_interval
            prev_interval_var = self._ewma_interval_variance
            self._update_ewma_interval(interval)
        else:
            prev_interval_mean = self._ewma_interval
            prev_interval_var = self._ewma_interval_variance

        # Check volume anomaly against the pre-update baseline
        alert = self._check_volume_anomaly(
            amt, self._deposit_amounts,
            prev_mean, prev_var,
            prev_count, "deposit",
        )
        if alert is not None:
            alert.metrics["sender"] = sender
            self._alerts.append(alert)
            return alert

        # Check frequency anomaly (using pre-update interval EWMA)
        if interval is not None:
            freq_alert = self._check_frequency_anomaly_with(
                interval, ts, prev_interval_mean, prev_interval_var,
            )
            if freq_alert is not None:
                freq_alert.metrics["sender"] = sender
                self._alerts.append(freq_alert)
                return freq_alert

        return None

    def observe_withdrawal(
        self,
        amount: int,
        recipient: str,
        timestamp: Optional[float] = None,
    ) -> Optional[SafetyAlert]:
        """Record a withdrawal and check for anomalies.

        Parameters
        ----------
        amount : int
            Withdrawal amount in wei.
        recipient : str
            Recipient Ethereum address.
        timestamp : float, optional
            Observation time.

        Returns
        -------
        SafetyAlert or None
        """
        ts = timestamp if timestamp is not None else time.time()
        amt = float(amount)

        # Snapshot BEFORE update
        prev_mean = self._ewma_withdrawal
        prev_var = self._ewma_withdrawal_variance
        prev_count = self._withdrawal_count

        self._withdrawal_amounts.append(amt)
        self._withdrawal_count += 1
        self._update_ewma_withdrawal(amt)

        alert = self._check_volume_anomaly(
            amt, self._withdrawal_amounts,
            prev_mean, prev_var,
            prev_count, "withdrawal",
        )
        if alert is not None:
            alert.metrics["recipient"] = recipient
            self._alerts.append(alert)
            return alert

        return None

    def observe_failed_attempt(
        self,
        operation: str,
        error: str,
        timestamp: Optional[float] = None,
    ) -> Optional[SafetyAlert]:
        """Record a failed operation and check for attack patterns.

        Generates an alert if more than *_failure_burst_threshold*
        failures have occurred in the last 60 seconds.

        Parameters
        ----------
        operation : str
            E.g. ``"deposit"`` or ``"withdrawal"``.
        error : str
            Error description.
        timestamp : float, optional
            Observation time.

        Returns
        -------
        SafetyAlert or None
        """
        ts = timestamp if timestamp is not None else time.time()
        self._recent_failures.append(ts)

        # Count failures in the last 60 seconds
        cutoff = ts - 60.0
        recent = sum(1 for t in self._recent_failures if t >= cutoff)

        if recent >= self._failure_burst_threshold:
            severity = (
                AlertSeverity.CRITICAL if recent >= self._failure_burst_threshold * 2
                else AlertSeverity.WARNING
            )
            alert = SafetyAlert(
                timestamp=ts,
                severity=severity,
                source="anomaly_detector",
                message=(
                    f"Failure burst detected: {recent} failures in 60s "
                    f"(operation={operation}, latest error: {error})"
                ),
                metrics={
                    "recent_failures": recent,
                    "operation": operation,
                    "burst_threshold": self._failure_burst_threshold,
                },
            )
            self._alerts.append(alert)
            return alert

        return None

    # ── Properties ───────────────────────────────────────────────────────

    @property
    def stats(self) -> dict:
        """Current detector statistics."""
        return {
            "deposit_count": self._deposit_count,
            "withdrawal_count": self._withdrawal_count,
            "ewma_deposit": round(self._ewma_deposit, 4),
            "ewma_deposit_stddev": round(math.sqrt(max(self._ewma_variance, 0)), 4),
            "ewma_withdrawal": round(self._ewma_withdrawal, 4),
            "ewma_withdrawal_stddev": round(
                math.sqrt(max(self._ewma_withdrawal_variance, 0)), 4,
            ),
            "ewma_interval": round(self._ewma_interval, 4),
            "alerts_generated": len(self._alerts),
        }

    # ── Internal helpers ─────────────────────────────────────────────────

    def _update_ewma_deposit(self, value: float) -> None:
        """Update EWMA mean and variance for deposits."""
        alpha = self.ewma_alpha
        if self._deposit_count == 1:
            self._ewma_deposit = value
            self._ewma_variance = 0.0
        else:
            diff = value - self._ewma_deposit
            self._ewma_deposit += alpha * diff
            self._ewma_variance = (1 - alpha) * (self._ewma_variance + alpha * diff * diff)

    def _update_ewma_withdrawal(self, value: float) -> None:
        """Update EWMA mean and variance for withdrawals."""
        alpha = self.ewma_alpha
        if self._withdrawal_count == 1:
            self._ewma_withdrawal = value
            self._ewma_withdrawal_variance = 0.0
        else:
            diff = value - self._ewma_withdrawal
            self._ewma_withdrawal += alpha * diff
            self._ewma_withdrawal_variance = (1 - alpha) * (
                self._ewma_withdrawal_variance + alpha * diff * diff
            )

    def _update_ewma_interval(self, value: float) -> None:
        """Update EWMA for inter-deposit intervals."""
        alpha = self.ewma_alpha
        if len(self._deposit_intervals) == 1:
            self._ewma_interval = value
            self._ewma_interval_variance = 0.0
        else:
            diff = value - self._ewma_interval
            self._ewma_interval += alpha * diff
            self._ewma_interval_variance = (1 - alpha) * (
                self._ewma_interval_variance + alpha * diff * diff
            )

    def _check_volume_anomaly(
        self,
        amount: float,
        history: Deque[float],
        ewma_mean: float,
        ewma_var: float,
        count: int,
        label: str,
    ) -> Optional[SafetyAlert]:
        """Check if *amount* is a statistical outlier using EWMA + z-score."""
        if count < self.min_samples:
            return None

        stddev = math.sqrt(max(ewma_var, 0))
        if stddev < 1e-12:
            # All values identical — no variance to detect anomalies against
            return None

        z_score = (amount - ewma_mean) / stddev

        if abs(z_score) >= self.z_score_threshold:
            severity = (
                AlertSeverity.CRITICAL
                if abs(z_score) >= self.z_score_threshold * 2
                else AlertSeverity.WARNING
            )
            alert = SafetyAlert(
                timestamp=time.time(),
                severity=severity,
                source="anomaly_detector",
                message=(
                    f"Volume anomaly on {label}: amount={amount:.0f}, "
                    f"z-score={z_score:.2f} (threshold=±{self.z_score_threshold})"
                ),
                metrics={
                    "amount": amount,
                    "z_score": round(z_score, 4),
                    "ewma_mean": round(ewma_mean, 4),
                    "ewma_stddev": round(stddev, 4),
                    "label": label,
                },
            )
            return alert

        return None

    def _check_frequency_anomaly_with(
        self,
        interval: float,
        timestamp: float,
        ewma_mean: float,
        ewma_var: float,
    ) -> Optional[SafetyAlert]:
        """Check if the inter-deposit interval is anomalously short.

        Uses *pre-update* EWMA statistics so the current observation
        doesn't pollute the baseline.
        """
        if len(self._deposit_intervals) < self.min_samples:
            return None

        stddev = math.sqrt(max(ewma_var, 0))
        if stddev < 1e-12:
            return None

        # A *negative* z-score means the interval is shorter than expected
        z_score = (interval - ewma_mean) / stddev

        if z_score <= -self.z_score_threshold:
            severity = (
                AlertSeverity.CRITICAL
                if z_score <= -self.z_score_threshold * 2
                else AlertSeverity.WARNING
            )
            alert = SafetyAlert(
                timestamp=timestamp,
                severity=severity,
                source="anomaly_detector",
                message=(
                    f"Frequency anomaly: interval={interval:.3f}s, "
                    f"z-score={z_score:.2f} (mean={self._ewma_interval:.3f}s)"
                ),
                metrics={
                    "interval": round(interval, 4),
                    "z_score": round(z_score, 4),
                    "ewma_interval": round(self._ewma_interval, 4),
                    "ewma_interval_stddev": round(stddev, 4),
                },
            )
            return alert

        return None

    def __repr__(self) -> str:
        return (
            f"AnomalyDetector(deposits={self._deposit_count}, "
            f"withdrawals={self._withdrawal_count}, "
            f"alerts={len(self._alerts)})"
        )


# ---------------------------------------------------------------------------
# RateLimitMonitor
# ---------------------------------------------------------------------------


class RateLimitMonitor:
    """Monitors rate-limit utilisation and predicts exhaustion.

    Generates warnings when:

    - Daily limit is > *warning_threshold* (default 80%) utilised.
    - Current velocity would exhaust the limit before the daily reset.
    - Per-tx limit is being consistently hit (potential DoS).

    Parameters
    ----------
    daily_limit : int
        Maximum daily bridge throughput in wei.
    per_tx_limit : int
        Maximum per-transaction amount in wei.
    warning_threshold : float
        Fraction of daily limit that triggers a warning (0.0–1.0).
    """

    def __init__(
        self,
        daily_limit: int,
        per_tx_limit: int,
        warning_threshold: float = 0.8,
    ) -> None:
        self.daily_limit = daily_limit
        self.per_tx_limit = per_tx_limit
        self.warning_threshold = warning_threshold

        self._daily_used: int = 0
        self._tx_count: int = 0
        self._per_tx_hits: int = 0  # times someone hit the per-tx cap
        self._day_start: float = time.time()
        self._tx_timestamps: Deque[float] = deque(maxlen=1000)
        self._alerts: List[SafetyAlert] = []

    # ── Public API ───────────────────────────────────────────────────────

    def record_transaction(self, amount: int) -> Optional[SafetyAlert]:
        """Record a bridge transaction and check utilisation.

        Parameters
        ----------
        amount : int
            Transaction amount in wei.

        Returns
        -------
        SafetyAlert or None
            An alert if a warning threshold is crossed.
        """
        now = time.time()
        self._daily_used += amount
        self._tx_count += 1
        self._tx_timestamps.append(now)

        if amount >= self.per_tx_limit:
            self._per_tx_hits += 1

        # Check utilisation
        if self.daily_limit > 0:
            utilisation = self._daily_used / self.daily_limit
        else:
            utilisation = 1.0 if self._daily_used > 0 else 0.0

        alert: Optional[SafetyAlert] = None

        if utilisation >= 1.0:
            alert = SafetyAlert(
                timestamp=now,
                severity=AlertSeverity.CRITICAL,
                source="rate_limit_monitor",
                message=(
                    f"Daily limit EXHAUSTED: used {self._daily_used} / {self.daily_limit} "
                    f"({utilisation:.1%})"
                ),
                metrics={
                    "daily_used": self._daily_used,
                    "daily_limit": self.daily_limit,
                    "utilisation": round(utilisation, 4),
                },
            )
        elif utilisation >= self.warning_threshold:
            severity = (
                AlertSeverity.CRITICAL if utilisation >= 0.95
                else AlertSeverity.WARNING
            )
            exhaustion = self.predict_exhaustion()
            alert = SafetyAlert(
                timestamp=now,
                severity=severity,
                source="rate_limit_monitor",
                message=(
                    f"Rate limit warning: {utilisation:.1%} of daily limit used "
                    f"({self._daily_used} / {self.daily_limit})"
                    + (
                        f", predicted exhaustion in {exhaustion:.0f}s"
                        if exhaustion is not None
                        else ""
                    )
                ),
                metrics={
                    "daily_used": self._daily_used,
                    "daily_limit": self.daily_limit,
                    "utilisation": round(utilisation, 4),
                    "predicted_exhaustion_seconds": exhaustion,
                },
            )

        if alert is not None:
            self._alerts.append(alert)

        return alert

    def predict_exhaustion(self) -> Optional[float]:
        """Predict when the daily limit will be exhausted.

        Uses the average transaction rate (amount / time) to project
        when remaining capacity will be consumed.

        Returns
        -------
        float or None
            Seconds from now until exhaustion, or ``None`` if no
            prediction can be made (e.g. no transactions yet or limit
            already reached).
        """
        if self.daily_limit <= 0:
            return 0.0

        remaining = self.daily_limit - self._daily_used
        if remaining <= 0:
            return 0.0

        now = time.time()
        elapsed = now - self._day_start
        if elapsed <= 0 or self._daily_used <= 0:
            return None

        rate = self._daily_used / elapsed  # wei per second
        if rate <= 0:
            return None

        return remaining / rate

    def reset_daily(self) -> None:
        """Called when the daily limit resets (new 24h window)."""
        self._daily_used = 0
        self._tx_count = 0
        self._per_tx_hits = 0
        self._day_start = time.time()
        self._tx_timestamps.clear()

    @property
    def stats(self) -> dict:
        """Current rate-limit statistics."""
        utilisation = 0.0
        if self.daily_limit > 0:
            utilisation = self._daily_used / self.daily_limit
        return {
            "daily_used": self._daily_used,
            "daily_limit": self.daily_limit,
            "per_tx_limit": self.per_tx_limit,
            "utilisation": round(utilisation, 4),
            "tx_count": self._tx_count,
            "per_tx_hits": self._per_tx_hits,
            "alerts_generated": len(self._alerts),
        }

    def __repr__(self) -> str:
        return (
            f"RateLimitMonitor(used={self._daily_used}/{self.daily_limit}, "
            f"txs={self._tx_count})"
        )


# ---------------------------------------------------------------------------
# ValidatorHealthMonitor
# ---------------------------------------------------------------------------


class ValidatorHealthMonitor:
    """Monitors validator liveness and attestation health.

    Generates alerts when:

    - A validator hasn't sent a heartbeat within the expected interval
      multiplied by *heartbeat_timeout_multiplier*.
    - The attestation success rate of a validator drops below 50%.
    - The number of active validators drops below *threshold*.

    Parameters
    ----------
    expected_validators : int
        Expected total number of validators (for quorum checks).
    threshold : int
        Minimum number of active validators needed.
    heartbeat_interval : float
        Expected seconds between heartbeats.
    heartbeat_timeout_multiplier : float
        Factor applied to *heartbeat_interval* to determine timeout.
    """

    def __init__(
        self,
        expected_validators: int = 6,
        threshold: int = 4,
        heartbeat_interval: float = 30.0,
        heartbeat_timeout_multiplier: float = 3.0,
    ) -> None:
        self.expected_validators = expected_validators
        self.threshold = threshold
        self.heartbeat_interval = heartbeat_interval
        self.heartbeat_timeout = heartbeat_interval * heartbeat_timeout_multiplier

        self._last_heartbeats: Dict[str, float] = {}
        self._attestation_results: Dict[str, Deque[bool]] = {}
        self._alerts: List[SafetyAlert] = []

    # ── Public API ───────────────────────────────────────────────────────

    def record_heartbeat(self, validator_did: str) -> None:
        """Record a heartbeat from a validator.

        Parameters
        ----------
        validator_did : str
            The DID of the validator.
        """
        self._last_heartbeats[validator_did] = time.time()
        # Ensure an attestation deque exists
        if validator_did not in self._attestation_results:
            self._attestation_results[validator_did] = deque(maxlen=100)

    def record_attestation(self, validator_did: str, success: bool) -> None:
        """Record an attestation result for a validator.

        Parameters
        ----------
        validator_did : str
            The DID of the validator.
        success : bool
            Whether the attestation was successful.
        """
        if validator_did not in self._attestation_results:
            self._attestation_results[validator_did] = deque(maxlen=100)
        self._attestation_results[validator_did].append(success)

    def check_health(self) -> List[SafetyAlert]:
        """Check all validators and return any alerts.

        This should be called periodically (e.g. every heartbeat interval).

        Returns
        -------
        list of SafetyAlert
            Zero or more alerts describing validator health issues.
        """
        now = time.time()
        alerts: List[SafetyAlert] = []

        # Check individual validator heartbeats
        for did, last_hb in self._last_heartbeats.items():
            elapsed = now - last_hb
            if elapsed > self.heartbeat_timeout:
                alert = SafetyAlert(
                    timestamp=now,
                    severity=AlertSeverity.WARNING,
                    source="validator_health",
                    message=(
                        f"Validator {did} heartbeat timeout: "
                        f"{elapsed:.1f}s since last heartbeat "
                        f"(timeout={self.heartbeat_timeout:.1f}s)"
                    ),
                    metrics={
                        "validator_did": did,
                        "elapsed": round(elapsed, 1),
                        "timeout": self.heartbeat_timeout,
                    },
                )
                alerts.append(alert)

        # Check attestation success rates
        for did, results in self._attestation_results.items():
            if len(results) < 5:
                continue
            success_rate = sum(1 for r in results if r) / len(results)
            if success_rate < 0.5:
                alert = SafetyAlert(
                    timestamp=now,
                    severity=AlertSeverity.WARNING,
                    source="validator_health",
                    message=(
                        f"Validator {did} low attestation success rate: "
                        f"{success_rate:.1%} ({sum(1 for r in results if r)}/{len(results)})"
                    ),
                    metrics={
                        "validator_did": did,
                        "success_rate": round(success_rate, 4),
                        "total_attestations": len(results),
                    },
                )
                alerts.append(alert)

        # Check validator count
        active = self.active_validators
        if active < self.threshold:
            severity = (
                AlertSeverity.EMERGENCY if active == 0
                else AlertSeverity.CRITICAL
            )
            alert = SafetyAlert(
                timestamp=now,
                severity=severity,
                source="validator_health",
                message=(
                    f"Active validators below threshold: "
                    f"{active}/{self.expected_validators} "
                    f"(threshold={self.threshold})"
                ),
                metrics={
                    "active_validators": active,
                    "expected": self.expected_validators,
                    "threshold": self.threshold,
                },
            )
            alerts.append(alert)

        self._alerts.extend(alerts)
        return alerts

    # ── Properties ───────────────────────────────────────────────────────

    @property
    def active_validators(self) -> int:
        """Number of validators with recent heartbeats (within timeout)."""
        now = time.time()
        return sum(
            1 for t in self._last_heartbeats.values()
            if (now - t) <= self.heartbeat_timeout
        )

    @property
    def stats(self) -> dict:
        """Current validator-health statistics."""
        return {
            "known_validators": len(self._last_heartbeats),
            "active_validators": self.active_validators,
            "expected_validators": self.expected_validators,
            "threshold": self.threshold,
            "alerts_generated": len(self._alerts),
        }

    def __repr__(self) -> str:
        return (
            f"ValidatorHealthMonitor(active={self.active_validators}/"
            f"{self.expected_validators}, threshold={self.threshold})"
        )


# ---------------------------------------------------------------------------
# BridgeSafetyManager
# ---------------------------------------------------------------------------


class BridgeSafetyManager:
    """Orchestrates all safety components for the bridge.

    Ties together circuit breakers, anomaly detection, rate-limit
    monitoring, and validator health into a single safety layer.

    When critical / emergency alerts are generated and *auto_pause_enabled*
    is ``True``, the manager will call ``contract_client.pause()`` to
    halt the on-chain bridge.

    Parameters
    ----------
    contract_client : object, optional
        A :class:`BridgeContractClient` (or duck-typed equivalent with an
        async ``pause()`` method).
    validator : object, optional
        A :class:`BridgeValidator` (or duck-typed equivalent with
        ``emergency_halt(reason)``).
    daily_limit : int
        Daily bridge throughput limit in wei.
    per_tx_limit : int
        Per-transaction bridge limit in wei.
    auto_pause_enabled : bool
        Whether to automatically pause the contract on EMERGENCY alerts.
    """

    def __init__(
        self,
        contract_client: Any = None,
        validator: Any = None,
        daily_limit: int = 100 * 10**18,
        per_tx_limit: int = 10 * 10**18,
        auto_pause_enabled: bool = True,
    ) -> None:
        self.contract_client = contract_client
        self.validator = validator

        # Circuit breakers
        self.deposit_breaker = CircuitBreaker(
            "deposit", failure_threshold=3, cooldown_seconds=120,
        )
        self.withdrawal_breaker = CircuitBreaker(
            "withdrawal", failure_threshold=3, cooldown_seconds=120,
        )
        self.sync_breaker = CircuitBreaker(
            "sync_committee", failure_threshold=2, cooldown_seconds=300,
        )

        # Sub-monitors
        self.anomaly_detector = AnomalyDetector()
        self.rate_monitor = RateLimitMonitor(daily_limit, per_tx_limit)
        self.validator_monitor = ValidatorHealthMonitor()

        # Alert aggregation
        self._alerts: List[SafetyAlert] = []
        self._auto_pause_enabled = auto_pause_enabled
        self._paused_by_safety: bool = False

    # ── Pre-flight checks ────────────────────────────────────────────────

    async def check_deposit(self, amount: int, sender: str) -> bool:
        """Pre-flight check before processing a deposit.

        Returns ``True`` if safe to proceed, ``False`` if the operation
        should be blocked.
        """
        # Circuit breaker gate
        if not self.deposit_breaker.is_available():
            logger.warning("Deposit blocked: circuit breaker OPEN")
            return False

        # Anomaly check
        alert = self.anomaly_detector.observe_deposit(amount, sender)
        if alert is not None:
            await self._handle_alert(alert)
            if alert.severity in (AlertSeverity.CRITICAL, AlertSeverity.EMERGENCY):
                return False

        # Rate-limit check
        rate_alert = self.rate_monitor.record_transaction(amount)
        if rate_alert is not None:
            await self._handle_alert(rate_alert)
            if rate_alert.severity == AlertSeverity.CRITICAL:
                return False

        return True

    async def check_withdrawal(self, amount: int, recipient: str) -> bool:
        """Pre-flight check before processing a withdrawal.

        Returns ``True`` if safe to proceed.
        """
        # Circuit breaker gate
        if not self.withdrawal_breaker.is_available():
            logger.warning("Withdrawal blocked: circuit breaker OPEN")
            return False

        # Anomaly check
        alert = self.anomaly_detector.observe_withdrawal(amount, recipient)
        if alert is not None:
            await self._handle_alert(alert)
            if alert.severity in (AlertSeverity.CRITICAL, AlertSeverity.EMERGENCY):
                return False

        # Rate-limit check
        rate_alert = self.rate_monitor.record_transaction(amount)
        if rate_alert is not None:
            await self._handle_alert(rate_alert)
            if rate_alert.severity == AlertSeverity.CRITICAL:
                return False

        return True

    # ── Result recording ─────────────────────────────────────────────────

    def record_deposit_result(
        self, success: bool, amount: int = 0, sender: str = "",
    ) -> None:
        """Record the outcome of a deposit operation."""
        if success:
            self.deposit_breaker.record_success()
        else:
            self.deposit_breaker.record_failure()
            self.anomaly_detector.observe_failed_attempt(
                "deposit", f"deposit failed (amount={amount}, sender={sender})",
            )

    def record_withdrawal_result(
        self, success: bool, amount: int = 0, recipient: str = "",
    ) -> None:
        """Record the outcome of a withdrawal operation."""
        if success:
            self.withdrawal_breaker.record_success()
        else:
            self.withdrawal_breaker.record_failure()
            self.anomaly_detector.observe_failed_attempt(
                "withdrawal",
                f"withdrawal failed (amount={amount}, recipient={recipient})",
            )

    # ── Alert handling ───────────────────────────────────────────────────

    async def _handle_alert(self, alert: SafetyAlert) -> None:
        """Process an alert — may trigger auto-pause on EMERGENCY."""
        self._alerts.append(alert)
        logger.log(
            logging.CRITICAL if alert.severity == AlertSeverity.EMERGENCY
            else logging.WARNING,
            "Safety alert [%s/%s]: %s",
            alert.severity.value, alert.source, alert.message,
        )

        if (
            alert.severity == AlertSeverity.EMERGENCY
            and self._auto_pause_enabled
        ):
            await self._auto_pause(alert.message)

    async def _auto_pause(self, reason: str) -> None:
        """Auto-pause the bridge contract and/or trigger emergency halt."""
        if self._paused_by_safety:
            return  # already paused

        logger.critical("AUTO-PAUSE triggered: %s", reason)
        self._paused_by_safety = True

        # Pause on-chain contract
        if self.contract_client is not None:
            try:
                await self.contract_client.pause()
                logger.critical("Bridge contract paused by safety system")
            except Exception as exc:
                logger.error("Failed to pause contract: %s", exc)

        # Halt the validator
        if self.validator is not None:
            try:
                await self.validator.emergency_halt(
                    f"Auto-halt by safety system: {reason}"
                )
            except Exception as exc:
                logger.error("Failed to emergency halt validator: %s", exc)

    # ── Query ────────────────────────────────────────────────────────────

    def get_alerts(
        self,
        since: float = 0,
        severity: Optional[AlertSeverity] = None,
    ) -> List[SafetyAlert]:
        """Get alerts, optionally filtered by time and severity.

        Parameters
        ----------
        since : float
            Only return alerts after this Unix timestamp.
        severity : AlertSeverity, optional
            Only return alerts of this severity.

        Returns
        -------
        list of SafetyAlert
        """
        alerts = self._alerts
        if since > 0:
            alerts = [a for a in alerts if a.timestamp >= since]
        if severity is not None:
            alerts = [a for a in alerts if a.severity == severity]
        return alerts

    @property
    def health_report(self) -> dict:
        """Comprehensive safety health report."""
        return {
            "paused_by_safety": self._paused_by_safety,
            "auto_pause_enabled": self._auto_pause_enabled,
            "circuit_breakers": {
                "deposit": self.deposit_breaker.stats,
                "withdrawal": self.withdrawal_breaker.stats,
                "sync_committee": self.sync_breaker.stats,
            },
            "anomaly_detector": self.anomaly_detector.stats,
            "rate_limit": self.rate_monitor.stats,
            "validator_health": self.validator_monitor.stats,
            "total_alerts": len(self._alerts),
        }

    def reset_all(self) -> None:
        """Reset all monitors and breakers (for testing or recovery)."""
        self.deposit_breaker.reset()
        self.withdrawal_breaker.reset()
        self.sync_breaker.reset()
        self.anomaly_detector = AnomalyDetector()
        self.rate_monitor = RateLimitMonitor(
            self.rate_monitor.daily_limit,
            self.rate_monitor.per_tx_limit,
        )
        self.validator_monitor = ValidatorHealthMonitor()
        self._alerts.clear()
        self._paused_by_safety = False

    def __repr__(self) -> str:
        return (
            f"BridgeSafetyManager("
            f"paused={self._paused_by_safety}, "
            f"alerts={len(self._alerts)}, "
            f"breakers=[{self.deposit_breaker.state.value}/"
            f"{self.withdrawal_breaker.state.value}/"
            f"{self.sync_breaker.state.value}])"
        )
