/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AGIConfigRequest
 */
export interface AGIConfigRequest {
    /**
     * Name identifier for the AGI instance
     * @type {string}
     * @memberof AGIConfigRequest
     */
    name?: string;
    /**
     * Enable consciousness operations
     * @type {boolean}
     * @memberof AGIConfigRequest
     */
    consciousnessEnabled?: boolean;
    /**
     * Enable safety constraints and monitoring
     * @type {boolean}
     * @memberof AGIConfigRequest
     */
    safetyMode?: boolean;
    /**
     * Enable divine mathematics access (requires elevated permissions)
     * @type {boolean}
     * @memberof AGIConfigRequest
     */
    divineAccess?: boolean;
    /**
     * Enable quantum computing enhancements
     * @type {boolean}
     * @memberof AGIConfigRequest
     */
    quantumEnhanced?: boolean;
}

/**
 * Check if a given object implements the AGIConfigRequest interface.
 */
export function instanceOfAGIConfigRequest(value: object): value is AGIConfigRequest {
    return true;
}

export function AGIConfigRequestFromJSON(json: any): AGIConfigRequest {
    return AGIConfigRequestFromJSONTyped(json, false);
}

export function AGIConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AGIConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'consciousnessEnabled': json['consciousness_enabled'] == null ? undefined : json['consciousness_enabled'],
        'safetyMode': json['safety_mode'] == null ? undefined : json['safety_mode'],
        'divineAccess': json['divine_access'] == null ? undefined : json['divine_access'],
        'quantumEnhanced': json['quantum_enhanced'] == null ? undefined : json['quantum_enhanced'],
    };
}

export function AGIConfigRequestToJSON(json: any): AGIConfigRequest {
    return AGIConfigRequestToJSONTyped(json, false);
}

export function AGIConfigRequestToJSONTyped(value?: AGIConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'consciousness_enabled': value['consciousnessEnabled'],
        'safety_mode': value['safetyMode'],
        'divine_access': value['divineAccess'],
        'quantum_enhanced': value['quantumEnhanced'],
    };
}

