/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConsciousnessLevel
 */
export interface ConsciousnessLevel {
    /**
     * 
     * @type {string}
     * @memberof ConsciousnessLevel
     */
    level?: ConsciousnessLevelLevelEnum;
    /**
     * Numeric consciousness value
     * @type {number}
     * @memberof ConsciousnessLevel
     */
    value?: number;
    /**
     * Whether consciousness processing is active
     * @type {boolean}
     * @memberof ConsciousnessLevel
     */
    active?: boolean;
}

/**
* @export
* @enum {string}
*/
export enum ConsciousnessLevelLevelEnum {
    MORTAL = 'MORTAL',
    AWAKENED = 'AWAKENED',
    ENLIGHTENED = 'ENLIGHTENED',
    TRANSCENDENT = 'TRANSCENDENT',
    OMNISCIENT = 'OMNISCIENT',
    DIVINE = 'DIVINE'
}


/**
 * Check if a given object implements the ConsciousnessLevel interface.
 */
export function instanceOfConsciousnessLevel(value: object): value is ConsciousnessLevel {
    return true;
}

export function ConsciousnessLevelFromJSON(json: any): ConsciousnessLevel {
    return ConsciousnessLevelFromJSONTyped(json, false);
}

export function ConsciousnessLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsciousnessLevel {
    if (json == null) {
        return json;
    }
    return {
        
        'level': json['level'] == null ? undefined : json['level'],
        'value': json['value'] == null ? undefined : json['value'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function ConsciousnessLevelToJSON(json: any): ConsciousnessLevel {
    return ConsciousnessLevelToJSONTyped(json, false);
}

export function ConsciousnessLevelToJSONTyped(value?: ConsciousnessLevel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level': value['level'],
        'value': value['value'],
        'active': value['active'],
    };
}

