/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApiInfo200Response
 */
export interface GetApiInfo200Response {
    /**
     * 
     * @type {string}
     * @memberof GetApiInfo200Response
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetApiInfo200Response
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof GetApiInfo200Response
     */
    status?: string;
    /**
     * 
     * @type {object}
     * @memberof GetApiInfo200Response
     */
    endpoints?: object;
}

/**
 * Check if a given object implements the GetApiInfo200Response interface.
 */
export function instanceOfGetApiInfo200Response(value: object): value is GetApiInfo200Response {
    return true;
}

export function GetApiInfo200ResponseFromJSON(json: any): GetApiInfo200Response {
    return GetApiInfo200ResponseFromJSONTyped(json, false);
}

export function GetApiInfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiInfo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'status': json['status'] == null ? undefined : json['status'],
        'endpoints': json['endpoints'] == null ? undefined : json['endpoints'],
    };
}

export function GetApiInfo200ResponseToJSON(json: any): GetApiInfo200Response {
    return GetApiInfo200ResponseToJSONTyped(json, false);
}

export function GetApiInfo200ResponseToJSONTyped(value?: GetApiInfo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'version': value['version'],
        'status': value['status'],
        'endpoints': value['endpoints'],
    };
}

