/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HealthCheck200ResponseServices } from './HealthCheck200ResponseServices';
import {
    HealthCheck200ResponseServicesFromJSON,
    HealthCheck200ResponseServicesFromJSONTyped,
    HealthCheck200ResponseServicesToJSON,
    HealthCheck200ResponseServicesToJSONTyped,
} from './HealthCheck200ResponseServices';

/**
 * 
 * @export
 * @interface HealthCheck200Response
 */
export interface HealthCheck200Response {
    /**
     * 
     * @type {string}
     * @memberof HealthCheck200Response
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof HealthCheck200Response
     */
    timestamp?: Date;
    /**
     * 
     * @type {HealthCheck200ResponseServices}
     * @memberof HealthCheck200Response
     */
    services?: HealthCheck200ResponseServices;
}

/**
 * Check if a given object implements the HealthCheck200Response interface.
 */
export function instanceOfHealthCheck200Response(value: object): value is HealthCheck200Response {
    return true;
}

export function HealthCheck200ResponseFromJSON(json: any): HealthCheck200Response {
    return HealthCheck200ResponseFromJSONTyped(json, false);
}

export function HealthCheck200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheck200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'services': json['services'] == null ? undefined : HealthCheck200ResponseServicesFromJSON(json['services']),
    };
}

export function HealthCheck200ResponseToJSON(json: any): HealthCheck200Response {
    return HealthCheck200ResponseToJSONTyped(json, false);
}

export function HealthCheck200ResponseToJSONTyped(value?: HealthCheck200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'services': HealthCheck200ResponseServicesToJSON(value['services']),
    };
}

