/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Reality
 */
export interface Reality {
    /**
     * Reality identifier
     * @type {string}
     * @memberof Reality
     */
    name?: string;
    /**
     * Number of dimensions
     * @type {number}
     * @memberof Reality
     */
    dimensions?: number;
    /**
     * Governing axioms
     * @type {Array<string>}
     * @memberof Reality
     */
    axioms?: Array<string>;
    /**
     * Base consciousness level
     * @type {number}
     * @memberof Reality
     */
    consciousnessLevel?: number;
}

/**
 * Check if a given object implements the Reality interface.
 */
export function instanceOfReality(value: object): value is Reality {
    return true;
}

export function RealityFromJSON(json: any): Reality {
    return RealityFromJSONTyped(json, false);
}

export function RealityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reality {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'dimensions': json['dimensions'] == null ? undefined : json['dimensions'],
        'axioms': json['axioms'] == null ? undefined : json['axioms'],
        'consciousnessLevel': json['consciousness_level'] == null ? undefined : json['consciousness_level'],
    };
}

export function RealityToJSON(json: any): Reality {
    return RealityToJSONTyped(json, false);
}

export function RealityToJSONTyped(value?: Reality | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'dimensions': value['dimensions'],
        'axioms': value['axioms'],
        'consciousness_level': value['consciousnessLevel'],
    };
}

