/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RealityRequest
 */
export interface RealityRequest {
    /**
     * Name for the new reality
     * @type {string}
     * @memberof RealityRequest
     */
    name: string;
    /**
     * Number of spatial dimensions
     * @type {number}
     * @memberof RealityRequest
     */
    dimensions?: number;
    /**
     * Mathematical axioms governing the reality
     * @type {Array<string>}
     * @memberof RealityRequest
     */
    axioms?: Array<string>;
    /**
     * Base consciousness level for the reality
     * @type {number}
     * @memberof RealityRequest
     */
    consciousnessLevel?: number;
}

/**
 * Check if a given object implements the RealityRequest interface.
 */
export function instanceOfRealityRequest(value: object): value is RealityRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RealityRequestFromJSON(json: any): RealityRequest {
    return RealityRequestFromJSONTyped(json, false);
}

export function RealityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RealityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'dimensions': json['dimensions'] == null ? undefined : json['dimensions'],
        'axioms': json['axioms'] == null ? undefined : json['axioms'],
        'consciousnessLevel': json['consciousness_level'] == null ? undefined : json['consciousness_level'],
    };
}

export function RealityRequestToJSON(json: any): RealityRequest {
    return RealityRequestToJSONTyped(json, false);
}

export function RealityRequestToJSONTyped(value?: RealityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'dimensions': value['dimensions'],
        'axioms': value['axioms'],
        'consciousness_level': value['consciousnessLevel'],
    };
}

