/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Response
 */
export interface Response {
    /**
     * Whether the operation was successful
     * @type {boolean}
     * @memberof Response
     */
    success: boolean;
    /**
     * Human-readable response message
     * @type {string}
     * @memberof Response
     */
    message: string;
    /**
     * Response data (varies by endpoint)
     * @type {{ [key: string]: any; }}
     * @memberof Response
     */
    data?: { [key: string]: any; };
    /**
     * ISO 8601 timestamp of the response
     * @type {Date}
     * @memberof Response
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the Response interface.
 */
export function instanceOfResponse(value: object): value is Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ResponseFromJSON(json: any): Response {
    return ResponseFromJSONTyped(json, false);
}

export function ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : json['data'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function ResponseToJSON(json: any): Response {
    return ResponseToJSONTyped(json, false);
}

export function ResponseToJSONTyped(value?: Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': value['data'],
        'timestamp': ((value['timestamp']).toISOString()),
    };
}

