/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebSocketMessage
 */
export interface WebSocketMessage {
    /**
     * 
     * @type {string}
     * @memberof WebSocketMessage
     */
    type: WebSocketMessageTypeEnum;
    /**
     * Message-specific data
     * @type {{ [key: string]: any; }}
     * @memberof WebSocketMessage
     */
    data?: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof WebSocketMessage
     */
    timestamp: Date;
}

/**
* @export
* @enum {string}
*/
export enum WebSocketMessageTypeEnum {
    thought = 'thought',
    consciousness_change = 'consciousness_change',
    reality_shift = 'reality_shift',
    error = 'error',
    status_update = 'status_update'
}


/**
 * Check if a given object implements the WebSocketMessage interface.
 */
export function instanceOfWebSocketMessage(value: object): value is WebSocketMessage {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function WebSocketMessageFromJSON(json: any): WebSocketMessage {
    return WebSocketMessageFromJSONTyped(json, false);
}

export function WebSocketMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebSocketMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'data': json['data'] == null ? undefined : json['data'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function WebSocketMessageToJSON(json: any): WebSocketMessage {
    return WebSocketMessageToJSONTyped(json, false);
}

export function WebSocketMessageToJSONTyped(value?: WebSocketMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'data': value['data'],
        'timestamp': ((value['timestamp']).toISOString()),
    };
}

