/*
Kenny AGI RDK API

REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

API version: 0.1.0-alpha
Contact: support@kenny-agi.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kennyagi

import (
	"encoding/json"
	"time"
)

// checks if the SystemStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemStatus{}

// SystemStatus struct for SystemStatus
type SystemStatus struct {
	Status *string `json:"status,omitempty"`
	// Status of individual modules
	Modules *map[string]string `json:"modules,omitempty"`
	Performance *SystemStatusPerformance `json:"performance,omitempty"`
	LastUpdated *time.Time `json:"last_updated,omitempty"`
}

// NewSystemStatus instantiates a new SystemStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemStatus() *SystemStatus {
	this := SystemStatus{}
	return &this
}

// NewSystemStatusWithDefaults instantiates a new SystemStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemStatusWithDefaults() *SystemStatus {
	this := SystemStatus{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SystemStatus) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatus) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SystemStatus) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SystemStatus) SetStatus(v string) {
	o.Status = &v
}

// GetModules returns the Modules field value if set, zero value otherwise.
func (o *SystemStatus) GetModules() map[string]string {
	if o == nil || IsNil(o.Modules) {
		var ret map[string]string
		return ret
	}
	return *o.Modules
}

// GetModulesOk returns a tuple with the Modules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatus) GetModulesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Modules) {
		return nil, false
	}
	return o.Modules, true
}

// HasModules returns a boolean if a field has been set.
func (o *SystemStatus) HasModules() bool {
	if o != nil && !IsNil(o.Modules) {
		return true
	}

	return false
}

// SetModules gets a reference to the given map[string]string and assigns it to the Modules field.
func (o *SystemStatus) SetModules(v map[string]string) {
	o.Modules = &v
}

// GetPerformance returns the Performance field value if set, zero value otherwise.
func (o *SystemStatus) GetPerformance() SystemStatusPerformance {
	if o == nil || IsNil(o.Performance) {
		var ret SystemStatusPerformance
		return ret
	}
	return *o.Performance
}

// GetPerformanceOk returns a tuple with the Performance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatus) GetPerformanceOk() (*SystemStatusPerformance, bool) {
	if o == nil || IsNil(o.Performance) {
		return nil, false
	}
	return o.Performance, true
}

// HasPerformance returns a boolean if a field has been set.
func (o *SystemStatus) HasPerformance() bool {
	if o != nil && !IsNil(o.Performance) {
		return true
	}

	return false
}

// SetPerformance gets a reference to the given SystemStatusPerformance and assigns it to the Performance field.
func (o *SystemStatus) SetPerformance(v SystemStatusPerformance) {
	o.Performance = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *SystemStatus) GetLastUpdated() time.Time {
	if o == nil || IsNil(o.LastUpdated) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatus) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *SystemStatus) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given time.Time and assigns it to the LastUpdated field.
func (o *SystemStatus) SetLastUpdated(v time.Time) {
	o.LastUpdated = &v
}

func (o SystemStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Modules) {
		toSerialize["modules"] = o.Modules
	}
	if !IsNil(o.Performance) {
		toSerialize["performance"] = o.Performance
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["last_updated"] = o.LastUpdated
	}
	return toSerialize, nil
}

type NullableSystemStatus struct {
	value *SystemStatus
	isSet bool
}

func (v NullableSystemStatus) Get() *SystemStatus {
	return v.value
}

func (v *NullableSystemStatus) Set(val *SystemStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemStatus(val *SystemStatus) *NullableSystemStatus {
	return &NullableSystemStatus{value: val, isSet: true}
}

func (v NullableSystemStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


