/*
Kenny AGI RDK API

REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

API version: 0.1.0-alpha
Contact: support@kenny-agi.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kennyagi

import (
	"encoding/json"
)

// checks if the GetApiInfo200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetApiInfo200Response{}

// GetApiInfo200Response struct for GetApiInfo200Response
type GetApiInfo200Response struct {
	Name *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
	Status *string `json:"status,omitempty"`
	Endpoints map[string]interface{} `json:"endpoints,omitempty"`
}

// NewGetApiInfo200Response instantiates a new GetApiInfo200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetApiInfo200Response() *GetApiInfo200Response {
	this := GetApiInfo200Response{}
	return &this
}

// NewGetApiInfo200ResponseWithDefaults instantiates a new GetApiInfo200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetApiInfo200ResponseWithDefaults() *GetApiInfo200Response {
	this := GetApiInfo200Response{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetApiInfo200Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiInfo200Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetApiInfo200Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetApiInfo200Response) SetName(v string) {
	o.Name = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *GetApiInfo200Response) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiInfo200Response) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *GetApiInfo200Response) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *GetApiInfo200Response) SetVersion(v string) {
	o.Version = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetApiInfo200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiInfo200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetApiInfo200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetApiInfo200Response) SetStatus(v string) {
	o.Status = &v
}

// GetEndpoints returns the Endpoints field value if set, zero value otherwise.
func (o *GetApiInfo200Response) GetEndpoints() map[string]interface{} {
	if o == nil || IsNil(o.Endpoints) {
		var ret map[string]interface{}
		return ret
	}
	return o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiInfo200Response) GetEndpointsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Endpoints) {
		return map[string]interface{}{}, false
	}
	return o.Endpoints, true
}

// HasEndpoints returns a boolean if a field has been set.
func (o *GetApiInfo200Response) HasEndpoints() bool {
	if o != nil && !IsNil(o.Endpoints) {
		return true
	}

	return false
}

// SetEndpoints gets a reference to the given map[string]interface{} and assigns it to the Endpoints field.
func (o *GetApiInfo200Response) SetEndpoints(v map[string]interface{}) {
	o.Endpoints = v
}

func (o GetApiInfo200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetApiInfo200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Endpoints) {
		toSerialize["endpoints"] = o.Endpoints
	}
	return toSerialize, nil
}

type NullableGetApiInfo200Response struct {
	value *GetApiInfo200Response
	isSet bool
}

func (v NullableGetApiInfo200Response) Get() *GetApiInfo200Response {
	return v.value
}

func (v *NullableGetApiInfo200Response) Set(val *GetApiInfo200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetApiInfo200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetApiInfo200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetApiInfo200Response(val *GetApiInfo200Response) *NullableGetApiInfo200Response {
	return &NullableGetApiInfo200Response{value: val, isSet: true}
}

func (v NullableGetApiInfo200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetApiInfo200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


