/*
Kenny AGI RDK API

REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

API version: 0.1.0-alpha
Contact: support@kenny-agi.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kennyagi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WebSocketMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSocketMessage{}

// WebSocketMessage struct for WebSocketMessage
type WebSocketMessage struct {
	Type string `json:"type"`
	// Message-specific data
	Data map[string]interface{} `json:"data,omitempty"`
	Timestamp time.Time `json:"timestamp"`
}

type _WebSocketMessage WebSocketMessage

// NewWebSocketMessage instantiates a new WebSocketMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSocketMessage(type_ string, timestamp time.Time) *WebSocketMessage {
	this := WebSocketMessage{}
	this.Type = type_
	this.Timestamp = timestamp
	return &this
}

// NewWebSocketMessageWithDefaults instantiates a new WebSocketMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSocketMessageWithDefaults() *WebSocketMessage {
	this := WebSocketMessage{}
	return &this
}

// GetType returns the Type field value
func (o *WebSocketMessage) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WebSocketMessage) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WebSocketMessage) SetType(v string) {
	o.Type = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *WebSocketMessage) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketMessage) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *WebSocketMessage) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *WebSocketMessage) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetTimestamp returns the Timestamp field value
func (o *WebSocketMessage) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *WebSocketMessage) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *WebSocketMessage) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

func (o WebSocketMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSocketMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	toSerialize["timestamp"] = o.Timestamp
	return toSerialize, nil
}

func (o *WebSocketMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebSocketMessage := _WebSocketMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebSocketMessage)

	if err != nil {
		return err
	}

	*o = WebSocketMessage(varWebSocketMessage)

	return err
}

type NullableWebSocketMessage struct {
	value *WebSocketMessage
	isSet bool
}

func (v NullableWebSocketMessage) Get() *WebSocketMessage {
	return v.value
}

func (v *NullableWebSocketMessage) Set(val *WebSocketMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSocketMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSocketMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSocketMessage(val *WebSocketMessage) *NullableWebSocketMessage {
	return &NullableWebSocketMessage{value: val, isSet: true}
}

func (v NullableWebSocketMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSocketMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


