/*
Kenny AGI RDK API

REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

API version: 0.1.0-alpha
Contact: support@kenny-agi.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kennyagi

import (
	"encoding/json"
)

// checks if the HealthCheck200ResponseServices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthCheck200ResponseServices{}

// HealthCheck200ResponseServices struct for HealthCheck200ResponseServices
type HealthCheck200ResponseServices struct {
	Api *string `json:"api,omitempty"`
	Agi *string `json:"agi,omitempty"`
}

// NewHealthCheck200ResponseServices instantiates a new HealthCheck200ResponseServices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthCheck200ResponseServices() *HealthCheck200ResponseServices {
	this := HealthCheck200ResponseServices{}
	return &this
}

// NewHealthCheck200ResponseServicesWithDefaults instantiates a new HealthCheck200ResponseServices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthCheck200ResponseServicesWithDefaults() *HealthCheck200ResponseServices {
	this := HealthCheck200ResponseServices{}
	return &this
}

// GetApi returns the Api field value if set, zero value otherwise.
func (o *HealthCheck200ResponseServices) GetApi() string {
	if o == nil || IsNil(o.Api) {
		var ret string
		return ret
	}
	return *o.Api
}

// GetApiOk returns a tuple with the Api field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthCheck200ResponseServices) GetApiOk() (*string, bool) {
	if o == nil || IsNil(o.Api) {
		return nil, false
	}
	return o.Api, true
}

// HasApi returns a boolean if a field has been set.
func (o *HealthCheck200ResponseServices) HasApi() bool {
	if o != nil && !IsNil(o.Api) {
		return true
	}

	return false
}

// SetApi gets a reference to the given string and assigns it to the Api field.
func (o *HealthCheck200ResponseServices) SetApi(v string) {
	o.Api = &v
}

// GetAgi returns the Agi field value if set, zero value otherwise.
func (o *HealthCheck200ResponseServices) GetAgi() string {
	if o == nil || IsNil(o.Agi) {
		var ret string
		return ret
	}
	return *o.Agi
}

// GetAgiOk returns a tuple with the Agi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthCheck200ResponseServices) GetAgiOk() (*string, bool) {
	if o == nil || IsNil(o.Agi) {
		return nil, false
	}
	return o.Agi, true
}

// HasAgi returns a boolean if a field has been set.
func (o *HealthCheck200ResponseServices) HasAgi() bool {
	if o != nil && !IsNil(o.Agi) {
		return true
	}

	return false
}

// SetAgi gets a reference to the given string and assigns it to the Agi field.
func (o *HealthCheck200ResponseServices) SetAgi(v string) {
	o.Agi = &v
}

func (o HealthCheck200ResponseServices) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthCheck200ResponseServices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Api) {
		toSerialize["api"] = o.Api
	}
	if !IsNil(o.Agi) {
		toSerialize["agi"] = o.Agi
	}
	return toSerialize, nil
}

type NullableHealthCheck200ResponseServices struct {
	value *HealthCheck200ResponseServices
	isSet bool
}

func (v NullableHealthCheck200ResponseServices) Get() *HealthCheck200ResponseServices {
	return v.value
}

func (v *NullableHealthCheck200ResponseServices) Set(val *HealthCheck200ResponseServices) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthCheck200ResponseServices) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthCheck200ResponseServices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthCheck200ResponseServices(val *HealthCheck200ResponseServices) *NullableHealthCheck200ResponseServices {
	return &NullableHealthCheck200ResponseServices{value: val, isSet: true}
}

func (v NullableHealthCheck200ResponseServices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthCheck200ResponseServices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


