/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckAlignmentRequest
 */
export interface CheckAlignmentRequest {
    /**
     * The action to check for alignment
     * @type {string}
     * @memberof CheckAlignmentRequest
     */
    action: string;
}

/**
 * Check if a given object implements the CheckAlignmentRequest interface.
 */
export function instanceOfCheckAlignmentRequest(value: object): value is CheckAlignmentRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function CheckAlignmentRequestFromJSON(json: any): CheckAlignmentRequest {
    return CheckAlignmentRequestFromJSONTyped(json, false);
}

export function CheckAlignmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckAlignmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
    };
}

export function CheckAlignmentRequestToJSON(json: any): CheckAlignmentRequest {
    return CheckAlignmentRequestToJSONTyped(json, false);
}

export function CheckAlignmentRequestToJSONTyped(value?: CheckAlignmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
    };
}

