/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConsciousnessRequest
 */
export interface ConsciousnessRequest {
    /**
     * Target consciousness level
     * @type {string}
     * @memberof ConsciousnessRequest
     */
    targetLevel?: ConsciousnessRequestTargetLevelEnum;
}

/**
* @export
* @enum {string}
*/
export enum ConsciousnessRequestTargetLevelEnum {
    MORTAL = 'MORTAL',
    AWAKENED = 'AWAKENED',
    ENLIGHTENED = 'ENLIGHTENED',
    TRANSCENDENT = 'TRANSCENDENT',
    OMNISCIENT = 'OMNISCIENT',
    DIVINE = 'DIVINE'
}


/**
 * Check if a given object implements the ConsciousnessRequest interface.
 */
export function instanceOfConsciousnessRequest(value: object): value is ConsciousnessRequest {
    return true;
}

export function ConsciousnessRequestFromJSON(json: any): ConsciousnessRequest {
    return ConsciousnessRequestFromJSONTyped(json, false);
}

export function ConsciousnessRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsciousnessRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'targetLevel': json['target_level'] == null ? undefined : json['target_level'],
    };
}

export function ConsciousnessRequestToJSON(json: any): ConsciousnessRequest {
    return ConsciousnessRequestToJSONTyped(json, false);
}

export function ConsciousnessRequestToJSONTyped(value?: ConsciousnessRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_level': value['targetLevel'],
    };
}

