/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthCheck200ResponseServices
 */
export interface HealthCheck200ResponseServices {
    /**
     * 
     * @type {string}
     * @memberof HealthCheck200ResponseServices
     */
    api?: string;
    /**
     * 
     * @type {string}
     * @memberof HealthCheck200ResponseServices
     */
    agi?: string;
}

/**
 * Check if a given object implements the HealthCheck200ResponseServices interface.
 */
export function instanceOfHealthCheck200ResponseServices(value: object): value is HealthCheck200ResponseServices {
    return true;
}

export function HealthCheck200ResponseServicesFromJSON(json: any): HealthCheck200ResponseServices {
    return HealthCheck200ResponseServicesFromJSONTyped(json, false);
}

export function HealthCheck200ResponseServicesFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheck200ResponseServices {
    if (json == null) {
        return json;
    }
    return {
        
        'api': json['api'] == null ? undefined : json['api'],
        'agi': json['agi'] == null ? undefined : json['agi'],
    };
}

export function HealthCheck200ResponseServicesToJSON(json: any): HealthCheck200ResponseServices {
    return HealthCheck200ResponseServicesToJSONTyped(json, false);
}

export function HealthCheck200ResponseServicesToJSONTyped(value?: HealthCheck200ResponseServices | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api': value['api'],
        'agi': value['agi'],
    };
}

