/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemStatusPerformance
 */
export interface SystemStatusPerformance {
    /**
     * 
     * @type {number}
     * @memberof SystemStatusPerformance
     */
    cpuUsage?: number;
    /**
     * 
     * @type {number}
     * @memberof SystemStatusPerformance
     */
    memoryUsage?: number;
    /**
     * 
     * @type {number}
     * @memberof SystemStatusPerformance
     */
    consciousnessLevel?: number;
}

/**
 * Check if a given object implements the SystemStatusPerformance interface.
 */
export function instanceOfSystemStatusPerformance(value: object): value is SystemStatusPerformance {
    return true;
}

export function SystemStatusPerformanceFromJSON(json: any): SystemStatusPerformance {
    return SystemStatusPerformanceFromJSONTyped(json, false);
}

export function SystemStatusPerformanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemStatusPerformance {
    if (json == null) {
        return json;
    }
    return {
        
        'cpuUsage': json['cpu_usage'] == null ? undefined : json['cpu_usage'],
        'memoryUsage': json['memory_usage'] == null ? undefined : json['memory_usage'],
        'consciousnessLevel': json['consciousness_level'] == null ? undefined : json['consciousness_level'],
    };
}

export function SystemStatusPerformanceToJSON(json: any): SystemStatusPerformance {
    return SystemStatusPerformanceToJSONTyped(json, false);
}

export function SystemStatusPerformanceToJSONTyped(value?: SystemStatusPerformance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cpu_usage': value['cpuUsage'],
        'memory_usage': value['memoryUsage'],
        'consciousness_level': value['consciousnessLevel'],
    };
}

