/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemStatusPerformance } from './SystemStatusPerformance';
import {
    SystemStatusPerformanceFromJSON,
    SystemStatusPerformanceFromJSONTyped,
    SystemStatusPerformanceToJSON,
    SystemStatusPerformanceToJSONTyped,
} from './SystemStatusPerformance';

/**
 * 
 * @export
 * @interface SystemStatus
 */
export interface SystemStatus {
    /**
     * 
     * @type {string}
     * @memberof SystemStatus
     */
    status?: SystemStatusStatusEnum;
    /**
     * Status of individual modules
     * @type {{ [key: string]: string; }}
     * @memberof SystemStatus
     */
    modules?: { [key: string]: string; };
    /**
     * 
     * @type {SystemStatusPerformance}
     * @memberof SystemStatus
     */
    performance?: SystemStatusPerformance;
    /**
     * 
     * @type {Date}
     * @memberof SystemStatus
     */
    lastUpdated?: Date;
}

/**
* @export
* @enum {string}
*/
export enum SystemStatusStatusEnum {
    initializing = 'initializing',
    ready = 'ready',
    processing = 'processing',
    transcending = 'transcending',
    error = 'error'
}


/**
 * Check if a given object implements the SystemStatus interface.
 */
export function instanceOfSystemStatus(value: object): value is SystemStatus {
    return true;
}

export function SystemStatusFromJSON(json: any): SystemStatus {
    return SystemStatusFromJSONTyped(json, false);
}

export function SystemStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'modules': json['modules'] == null ? undefined : json['modules'],
        'performance': json['performance'] == null ? undefined : SystemStatusPerformanceFromJSON(json['performance']),
        'lastUpdated': json['last_updated'] == null ? undefined : (new Date(json['last_updated'])),
    };
}

export function SystemStatusToJSON(json: any): SystemStatus {
    return SystemStatusToJSONTyped(json, false);
}

export function SystemStatusToJSONTyped(value?: SystemStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'modules': value['modules'],
        'performance': SystemStatusPerformanceToJSON(value['performance']),
        'last_updated': value['lastUpdated'] == null ? undefined : ((value['lastUpdated']).toISOString()),
    };
}

