/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThinkRequest
 */
export interface ThinkRequest {
    /**
     * The thought prompt to process
     * @type {string}
     * @memberof ThinkRequest
     */
    prompt: string;
    /**
     * Additional context for the thought process
     * @type {{ [key: string]: any; }}
     * @memberof ThinkRequest
     */
    context?: { [key: string]: any; };
}

/**
 * Check if a given object implements the ThinkRequest interface.
 */
export function instanceOfThinkRequest(value: object): value is ThinkRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function ThinkRequestFromJSON(json: any): ThinkRequest {
    return ThinkRequestFromJSONTyped(json, false);
}

export function ThinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'context': json['context'] == null ? undefined : json['context'],
    };
}

export function ThinkRequestToJSON(json: any): ThinkRequest {
    return ThinkRequestToJSONTyped(json, false);
}

export function ThinkRequestToJSONTyped(value?: ThinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'context': value['context'],
    };
}

