/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AGIConfigRequest,
  ErrorResponse,
  Response,
  ThinkRequest,
} from '../models/index';
import {
    AGIConfigRequestFromJSON,
    AGIConfigRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ResponseFromJSON,
    ResponseToJSON,
    ThinkRequestFromJSON,
    ThinkRequestToJSON,
} from '../models/index';

export interface InitializeAgiRequest {
    aGIConfigRequest: AGIConfigRequest;
}

export interface ProcessThoughtRequest {
    thinkRequest: ThinkRequest;
}

/**
 * AGICoreApi - interface
 * 
 * @export
 * @interface AGICoreApiInterface
 */
export interface AGICoreApiInterface {
    /**
     * Get current AGI system status and metrics
     * @summary Get AGI status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AGICoreApiInterface
     */
    getAgiStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>>;

    /**
     * Get current AGI system status and metrics
     * Get AGI status
     */
    getAgiStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response>;

    /**
     * Initialize the AGI system with custom configuration
     * @summary Initialize AGI system
     * @param {AGIConfigRequest} aGIConfigRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AGICoreApiInterface
     */
    initializeAgiRaw(requestParameters: InitializeAgiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>>;

    /**
     * Initialize the AGI system with custom configuration
     * Initialize AGI system
     */
    initializeAgi(requestParameters: InitializeAgiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response>;

    /**
     * Process a thought through the AGI system
     * @summary Process thought
     * @param {ThinkRequest} thinkRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AGICoreApiInterface
     */
    processThoughtRaw(requestParameters: ProcessThoughtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>>;

    /**
     * Process a thought through the AGI system
     * Process thought
     */
    processThought(requestParameters: ProcessThoughtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response>;

    /**
     * Safely shutdown the AGI system
     * @summary Shutdown AGI system
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AGICoreApiInterface
     */
    shutdownAgiRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>>;

    /**
     * Safely shutdown the AGI system
     * Shutdown AGI system
     */
    shutdownAgi(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response>;

}

/**
 * 
 */
export class AGICoreApi extends runtime.BaseAPI implements AGICoreApiInterface {

    /**
     * Get current AGI system status and metrics
     * Get AGI status
     */
    async getAgiStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/agi/status`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     * Get current AGI system status and metrics
     * Get AGI status
     */
    async getAgiStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.getAgiStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Initialize the AGI system with custom configuration
     * Initialize AGI system
     */
    async initializeAgiRaw(requestParameters: InitializeAgiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        if (requestParameters['aGIConfigRequest'] == null) {
            throw new runtime.RequiredError(
                'aGIConfigRequest',
                'Required parameter "aGIConfigRequest" was null or undefined when calling initializeAgi().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/agi/initialize`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AGIConfigRequestToJSON(requestParameters['aGIConfigRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     * Initialize the AGI system with custom configuration
     * Initialize AGI system
     */
    async initializeAgi(requestParameters: InitializeAgiRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.initializeAgiRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Process a thought through the AGI system
     * Process thought
     */
    async processThoughtRaw(requestParameters: ProcessThoughtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        if (requestParameters['thinkRequest'] == null) {
            throw new runtime.RequiredError(
                'thinkRequest',
                'Required parameter "thinkRequest" was null or undefined when calling processThought().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/agi/think`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ThinkRequestToJSON(requestParameters['thinkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     * Process a thought through the AGI system
     * Process thought
     */
    async processThought(requestParameters: ProcessThoughtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.processThoughtRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Safely shutdown the AGI system
     * Shutdown AGI system
     */
    async shutdownAgiRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/agi/shutdown`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     * Safely shutdown the AGI system
     * Shutdown AGI system
     */
    async shutdownAgi(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.shutdownAgiRaw(initOverrides);
        return await response.value();
    }

}
