/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  Response,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ResponseFromJSON,
    ResponseToJSON,
} from '../models/index';

export interface DetectEmergenceRequest {
    requestBody: { [key: string]: any; };
}

/**
 * EmergenceDetectionApi - interface
 * 
 * @export
 * @interface EmergenceDetectionApiInterface
 */
export interface EmergenceDetectionApiInterface {
    /**
     * Detect emergent patterns in provided data
     * @summary Detect emergence patterns
     * @param {{ [key: string]: any; }} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmergenceDetectionApiInterface
     */
    detectEmergenceRaw(requestParameters: DetectEmergenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>>;

    /**
     * Detect emergent patterns in provided data
     * Detect emergence patterns
     */
    detectEmergence(requestParameters: DetectEmergenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response>;

}

/**
 * 
 */
export class EmergenceDetectionApi extends runtime.BaseAPI implements EmergenceDetectionApiInterface {

    /**
     * Detect emergent patterns in provided data
     * Detect emergence patterns
     */
    async detectEmergenceRaw(requestParameters: DetectEmergenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling detectEmergence().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emergence/detect`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     * Detect emergent patterns in provided data
     * Detect emergence patterns
     */
    async detectEmergence(requestParameters: DetectEmergenceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.detectEmergenceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
