/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  RealityRequest,
  Response,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    RealityRequestFromJSON,
    RealityRequestToJSON,
    ResponseFromJSON,
    ResponseToJSON,
} from '../models/index';

export interface CreateRealityRequest {
    realityRequest: RealityRequest;
}

/**
 * RealityManipulationApi - interface
 * 
 * @export
 * @interface RealityManipulationApiInterface
 */
export interface RealityManipulationApiInterface {
    /**
     * Create a new mathematical reality with specified parameters
     * @summary Create reality
     * @param {RealityRequest} realityRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RealityManipulationApiInterface
     */
    createRealityRaw(requestParameters: CreateRealityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>>;

    /**
     * Create a new mathematical reality with specified parameters
     * Create reality
     */
    createReality(requestParameters: CreateRealityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response>;

    /**
     * List all created mathematical realities
     * @summary List realities
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RealityManipulationApiInterface
     */
    listRealitiesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>>;

    /**
     * List all created mathematical realities
     * List realities
     */
    listRealities(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response>;

}

/**
 * 
 */
export class RealityManipulationApi extends runtime.BaseAPI implements RealityManipulationApiInterface {

    /**
     * Create a new mathematical reality with specified parameters
     * Create reality
     */
    async createRealityRaw(requestParameters: CreateRealityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        if (requestParameters['realityRequest'] == null) {
            throw new runtime.RequiredError(
                'realityRequest',
                'Required parameter "realityRequest" was null or undefined when calling createReality().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/reality/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RealityRequestToJSON(requestParameters['realityRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new mathematical reality with specified parameters
     * Create reality
     */
    async createReality(requestParameters: CreateRealityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.createRealityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all created mathematical realities
     * List realities
     */
    async listRealitiesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/reality/list`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     * List all created mathematical realities
     * List realities
     */
    async listRealities(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.listRealitiesRaw(initOverrides);
        return await response.value();
    }

}
