/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  Response,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ResponseFromJSON,
    ResponseToJSON,
} from '../models/index';

/**
 * SelfImprovementApi - interface
 * 
 * @export
 * @interface SelfImprovementApiInterface
 */
export interface SelfImprovementApiInterface {
    /**
     * Get self-improvement performance metrics
     * @summary Get improvement metrics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SelfImprovementApiInterface
     */
    getImprovementMetricsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>>;

    /**
     * Get self-improvement performance metrics
     * Get improvement metrics
     */
    getImprovementMetrics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response>;

}

/**
 * 
 */
export class SelfImprovementApi extends runtime.BaseAPI implements SelfImprovementApiInterface {

    /**
     * Get self-improvement performance metrics
     * Get improvement metrics
     */
    async getImprovementMetricsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/improvement/metrics`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     * Get self-improvement performance metrics
     * Get improvement metrics
     */
    async getImprovementMetrics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.getImprovementMetricsRaw(initOverrides);
        return await response.value();
    }

}
