/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * WebSocketApi - interface
 * 
 * @export
 * @interface WebSocketApiInterface
 */
export interface WebSocketApiInterface {
    /**
     * WebSocket endpoint for real-time AGI updates and bidirectional communication.  **Connection**: `ws://localhost:8000/ws`  **Authentication**: Include `Authorization: Bearer <token>` header  **Message Format**: - Send: Raw text messages for AGI processing - Receive: JSON objects with type, data, and timestamp  **Message Types**: - `thought`: AGI thought processing result - `consciousness_change`: Consciousness level updates - `reality_shift`: Reality matrix changes - `error`: Error messages 
     * @summary WebSocket endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebSocketApiInterface
     */
    websocketConnectionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * WebSocket endpoint for real-time AGI updates and bidirectional communication.  **Connection**: `ws://localhost:8000/ws`  **Authentication**: Include `Authorization: Bearer <token>` header  **Message Format**: - Send: Raw text messages for AGI processing - Receive: JSON objects with type, data, and timestamp  **Message Types**: - `thought`: AGI thought processing result - `consciousness_change`: Consciousness level updates - `reality_shift`: Reality matrix changes - `error`: Error messages 
     * WebSocket endpoint
     */
    websocketConnection(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class WebSocketApi extends runtime.BaseAPI implements WebSocketApiInterface {

    /**
     * WebSocket endpoint for real-time AGI updates and bidirectional communication.  **Connection**: `ws://localhost:8000/ws`  **Authentication**: Include `Authorization: Bearer <token>` header  **Message Format**: - Send: Raw text messages for AGI processing - Receive: JSON objects with type, data, and timestamp  **Message Types**: - `thought`: AGI thought processing result - `consciousness_change`: Consciousness level updates - `reality_shift`: Reality matrix changes - `error`: Error messages 
     * WebSocket endpoint
     */
    async websocketConnectionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ws`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * WebSocket endpoint for real-time AGI updates and bidirectional communication.  **Connection**: `ws://localhost:8000/ws`  **Authentication**: Include `Authorization: Bearer <token>` header  **Message Format**: - Send: Raw text messages for AGI processing - Receive: JSON objects with type, data, and timestamp  **Message Types**: - `thought`: AGI thought processing result - `consciousness_change`: Consciousness level updates - `reality_shift`: Reality matrix changes - `error`: Error messages 
     * WebSocket endpoint
     */
    async websocketConnection(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.websocketConnectionRaw(initOverrides);
    }

}
