# coding: utf-8

"""
    Kenny AGI RDK API

    REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

    The version of the OpenAPI document: 0.1.0-alpha
    Contact: support@kenny-agi.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kenny_agi_sdk.kenny_agi_sdk.models.get_api_info200_response import GetApiInfo200Response

class TestGetApiInfo200Response(unittest.TestCase):
    """GetApiInfo200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetApiInfo200Response:
        """Test GetApiInfo200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetApiInfo200Response`
        """
        model = GetApiInfo200Response()
        if include_optional:
            return GetApiInfo200Response(
                name = 'Kenny AGI RDK API',
                version = '0.1.0-alpha',
                status = 'operational',
                endpoints = None
            )
        else:
            return GetApiInfo200Response(
        )
        """

    def testGetApiInfo200Response(self):
        """Test GetApiInfo200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
