# coding: utf-8

"""
    Kenny AGI RDK API

    REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

    The version of the OpenAPI document: 0.1.0-alpha
    Contact: support@kenny-agi.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AGIConfigRequest(BaseModel):
    """
    AGIConfigRequest
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default='KennyAGI', description="Name identifier for the AGI instance")
    consciousness_enabled: Optional[StrictBool] = Field(default=True, description="Enable consciousness operations")
    safety_mode: Optional[StrictBool] = Field(default=True, description="Enable safety constraints and monitoring")
    divine_access: Optional[StrictBool] = Field(default=False, description="Enable divine mathematics access (requires elevated permissions)")
    quantum_enhanced: Optional[StrictBool] = Field(default=False, description="Enable quantum computing enhancements")
    __properties: ClassVar[List[str]] = ["name", "consciousness_enabled", "safety_mode", "divine_access", "quantum_enhanced"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AGIConfigRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AGIConfigRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name") if obj.get("name") is not None else 'KennyAGI',
            "consciousness_enabled": obj.get("consciousness_enabled") if obj.get("consciousness_enabled") is not None else True,
            "safety_mode": obj.get("safety_mode") if obj.get("safety_mode") is not None else True,
            "divine_access": obj.get("divine_access") if obj.get("divine_access") is not None else False,
            "quantum_enhanced": obj.get("quantum_enhanced") if obj.get("quantum_enhanced") is not None else False
        })
        return _obj


