# coding: utf-8

"""
    Kenny AGI RDK API

    REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

    The version of the OpenAPI document: 0.1.0-alpha
    Contact: support@kenny-agi.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from kenny_agi_sdk.models.system_status_performance import SystemStatusPerformance
from typing import Optional, Set
from typing_extensions import Self

class SystemStatus(BaseModel):
    """
    SystemStatus
    """ # noqa: E501
    status: Optional[StrictStr] = None
    modules: Optional[Dict[str, StrictStr]] = Field(default=None, description="Status of individual modules")
    performance: Optional[SystemStatusPerformance] = None
    last_updated: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["status", "modules", "performance", "last_updated"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['initializing', 'ready', 'processing', 'transcending', 'error']):
            raise ValueError("must be one of enum values ('initializing', 'ready', 'processing', 'transcending', 'error')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of performance
        if self.performance:
            _dict['performance'] = self.performance.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "modules": obj.get("modules"),
            "performance": SystemStatusPerformance.from_dict(obj["performance"]) if obj.get("performance") is not None else None,
            "last_updated": obj.get("last_updated")
        })
        return _obj


