# coding: utf-8

# flake8: noqa

"""
    Kenny AGI RDK API

    REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

    The version of the OpenAPI document: 0.1.0-alpha
    Contact: support@kenny-agi.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "AGICoreApi",
    "ConsciousnessApi",
    "ConstitutionalAIApi",
    "EmergenceDetectionApi",
    "RealityManipulationApi",
    "SelfImprovementApi",
    "SystemApi",
    "WebSocketApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AGIConfigRequest",
    "CheckAlignmentRequest",
    "ConsciousnessLevel",
    "ConsciousnessRequest",
    "ErrorResponse",
    "GetApiInfo200Response",
    "HealthCheck200Response",
    "HealthCheck200ResponseServices",
    "Reality",
    "RealityRequest",
    "Response",
    "SystemStatus",
    "SystemStatusPerformance",
    "ThinkRequest",
    "WebSocketMessage",
]

# import apis into sdk package
from kenny_agi_sdk.api.agi_core_api import AGICoreApi as AGICoreApi
from kenny_agi_sdk.api.consciousness_api import ConsciousnessApi as ConsciousnessApi
from kenny_agi_sdk.api.constitutional_ai_api import ConstitutionalAIApi as ConstitutionalAIApi
from kenny_agi_sdk.api.emergence_detection_api import EmergenceDetectionApi as EmergenceDetectionApi
from kenny_agi_sdk.api.reality_manipulation_api import RealityManipulationApi as RealityManipulationApi
from kenny_agi_sdk.api.self_improvement_api import SelfImprovementApi as SelfImprovementApi
from kenny_agi_sdk.api.system_api import SystemApi as SystemApi
from kenny_agi_sdk.api.web_socket_api import WebSocketApi as WebSocketApi

# import ApiClient
from kenny_agi_sdk.api_response import ApiResponse as ApiResponse
from kenny_agi_sdk.api_client import ApiClient as ApiClient
from kenny_agi_sdk.configuration import Configuration as Configuration
from kenny_agi_sdk.exceptions import OpenApiException as OpenApiException
from kenny_agi_sdk.exceptions import ApiTypeError as ApiTypeError
from kenny_agi_sdk.exceptions import ApiValueError as ApiValueError
from kenny_agi_sdk.exceptions import ApiKeyError as ApiKeyError
from kenny_agi_sdk.exceptions import ApiAttributeError as ApiAttributeError
from kenny_agi_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from kenny_agi_sdk.kenny_agi_sdk.models.agi_config_request import AGIConfigRequest as AGIConfigRequest
from kenny_agi_sdk.kenny_agi_sdk.models.check_alignment_request import CheckAlignmentRequest as CheckAlignmentRequest
from kenny_agi_sdk.kenny_agi_sdk.models.consciousness_level import ConsciousnessLevel as ConsciousnessLevel
from kenny_agi_sdk.kenny_agi_sdk.models.consciousness_request import ConsciousnessRequest as ConsciousnessRequest
from kenny_agi_sdk.kenny_agi_sdk.models.error_response import ErrorResponse as ErrorResponse
from kenny_agi_sdk.kenny_agi_sdk.models.get_api_info200_response import GetApiInfo200Response as GetApiInfo200Response
from kenny_agi_sdk.kenny_agi_sdk.models.health_check200_response import HealthCheck200Response as HealthCheck200Response
from kenny_agi_sdk.kenny_agi_sdk.models.health_check200_response_services import HealthCheck200ResponseServices as HealthCheck200ResponseServices
from kenny_agi_sdk.kenny_agi_sdk.models.reality import Reality as Reality
from kenny_agi_sdk.kenny_agi_sdk.models.reality_request import RealityRequest as RealityRequest
from kenny_agi_sdk.kenny_agi_sdk.models.response import Response as Response
from kenny_agi_sdk.kenny_agi_sdk.models.system_status import SystemStatus as SystemStatus
from kenny_agi_sdk.kenny_agi_sdk.models.system_status_performance import SystemStatusPerformance as SystemStatusPerformance
from kenny_agi_sdk.kenny_agi_sdk.models.think_request import ThinkRequest as ThinkRequest
from kenny_agi_sdk.kenny_agi_sdk.models.web_socket_message import WebSocketMessage as WebSocketMessage
