/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CheckAlignmentRequest,
  ErrorResponse,
  Response,
} from '../models/index';
import {
    CheckAlignmentRequestFromJSON,
    CheckAlignmentRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ResponseFromJSON,
    ResponseToJSON,
} from '../models/index';

export interface CheckAlignmentOperationRequest {
    checkAlignmentRequest: CheckAlignmentRequest;
}

/**
 * ConstitutionalAIApi - interface
 * 
 * @export
 * @interface ConstitutionalAIApiInterface
 */
export interface ConstitutionalAIApiInterface {
    /**
     * Check if an action aligns with constitutional values
     * @summary Check alignment
     * @param {CheckAlignmentRequest} checkAlignmentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConstitutionalAIApiInterface
     */
    checkAlignmentRaw(requestParameters: CheckAlignmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>>;

    /**
     * Check if an action aligns with constitutional values
     * Check alignment
     */
    checkAlignment(requestParameters: CheckAlignmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response>;

    /**
     * Get current constitutional AI status and constraints
     * @summary Get constitution status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConstitutionalAIApiInterface
     */
    getConstitutionStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>>;

    /**
     * Get current constitutional AI status and constraints
     * Get constitution status
     */
    getConstitutionStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response>;

}

/**
 * 
 */
export class ConstitutionalAIApi extends runtime.BaseAPI implements ConstitutionalAIApiInterface {

    /**
     * Check if an action aligns with constitutional values
     * Check alignment
     */
    async checkAlignmentRaw(requestParameters: CheckAlignmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        if (requestParameters['checkAlignmentRequest'] == null) {
            throw new runtime.RequiredError(
                'checkAlignmentRequest',
                'Required parameter "checkAlignmentRequest" was null or undefined when calling checkAlignment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/constitution/check`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CheckAlignmentRequestToJSON(requestParameters['checkAlignmentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     * Check if an action aligns with constitutional values
     * Check alignment
     */
    async checkAlignment(requestParameters: CheckAlignmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.checkAlignmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get current constitutional AI status and constraints
     * Get constitution status
     */
    async getConstitutionStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/constitution/status`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     * Get current constitutional AI status and constraints
     * Get constitution status
     */
    async getConstitutionStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.getConstitutionStatusRaw(initOverrides);
        return await response.value();
    }

}
