/* tslint:disable */
/* eslint-disable */
/**
 * Kenny AGI RDK API
 * REST API for Kenny\'s AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 
 *
 * The version of the OpenAPI document: 0.1.0-alpha
 * Contact: support@kenny-agi.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConsciousnessRequest,
  ErrorResponse,
  Response,
} from '../models/index';
import {
    ConsciousnessRequestFromJSON,
    ConsciousnessRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ResponseFromJSON,
    ResponseToJSON,
} from '../models/index';

export interface ElevateConsciousnessRequest {
    consciousnessRequest: ConsciousnessRequest;
}

/**
 * ConsciousnessApi - interface
 * 
 * @export
 * @interface ConsciousnessApiInterface
 */
export interface ConsciousnessApiInterface {
    /**
     * Elevate consciousness to target level with safety checks
     * @summary Elevate consciousness
     * @param {ConsciousnessRequest} consciousnessRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConsciousnessApiInterface
     */
    elevateConsciousnessRaw(requestParameters: ElevateConsciousnessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>>;

    /**
     * Elevate consciousness to target level with safety checks
     * Elevate consciousness
     */
    elevateConsciousness(requestParameters: ElevateConsciousnessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response>;

    /**
     * Get current consciousness level and status
     * @summary Get consciousness level
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConsciousnessApiInterface
     */
    getConsciousnessLevelRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>>;

    /**
     * Get current consciousness level and status
     * Get consciousness level
     */
    getConsciousnessLevel(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response>;

}

/**
 * 
 */
export class ConsciousnessApi extends runtime.BaseAPI implements ConsciousnessApiInterface {

    /**
     * Elevate consciousness to target level with safety checks
     * Elevate consciousness
     */
    async elevateConsciousnessRaw(requestParameters: ElevateConsciousnessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        if (requestParameters['consciousnessRequest'] == null) {
            throw new runtime.RequiredError(
                'consciousnessRequest',
                'Required parameter "consciousnessRequest" was null or undefined when calling elevateConsciousness().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/consciousness/elevate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConsciousnessRequestToJSON(requestParameters['consciousnessRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     * Elevate consciousness to target level with safety checks
     * Elevate consciousness
     */
    async elevateConsciousness(requestParameters: ElevateConsciousnessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.elevateConsciousnessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get current consciousness level and status
     * Get consciousness level
     */
    async getConsciousnessLevelRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/consciousness/level`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     * Get current consciousness level and status
     * Get consciousness level
     */
    async getConsciousnessLevel(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.getConsciousnessLevelRaw(initOverrides);
        return await response.value();
    }

}
