/*
Kenny AGI RDK API

REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

API version: 0.1.0-alpha
Contact: support@kenny-agi.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kennyagi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type WebSocketAPI interface {

	/*
	WebsocketConnection WebSocket endpoint

	WebSocket endpoint for real-time AGI updates and bidirectional communication.

**Connection**: `ws://localhost:8000/ws`

**Authentication**: Include `Authorization: Bearer <token>` header

**Message Format**:
- Send: Raw text messages for AGI processing
- Receive: JSON objects with type, data, and timestamp

**Message Types**:
- `thought`: AGI thought processing result
- `consciousness_change`: Consciousness level updates
- `reality_shift`: Reality matrix changes
- `error`: Error messages


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return WebSocketAPIWebsocketConnectionRequest
	*/
	WebsocketConnection(ctx context.Context) WebSocketAPIWebsocketConnectionRequest

	// WebsocketConnectionExecute executes the request
	WebsocketConnectionExecute(r WebSocketAPIWebsocketConnectionRequest) (*http.Response, error)
}

// WebSocketAPIService WebSocketAPI service
type WebSocketAPIService service

type WebSocketAPIWebsocketConnectionRequest struct {
	ctx context.Context
	ApiService WebSocketAPI
}

func (r WebSocketAPIWebsocketConnectionRequest) Execute() (*http.Response, error) {
	return r.ApiService.WebsocketConnectionExecute(r)
}

/*
WebsocketConnection WebSocket endpoint

WebSocket endpoint for real-time AGI updates and bidirectional communication.

**Connection**: `ws://localhost:8000/ws`

**Authentication**: Include `Authorization: Bearer <token>` header

**Message Format**:
- Send: Raw text messages for AGI processing
- Receive: JSON objects with type, data, and timestamp

**Message Types**:
- `thought`: AGI thought processing result
- `consciousness_change`: Consciousness level updates
- `reality_shift`: Reality matrix changes
- `error`: Error messages


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return WebSocketAPIWebsocketConnectionRequest
*/
func (a *WebSocketAPIService) WebsocketConnection(ctx context.Context) WebSocketAPIWebsocketConnectionRequest {
	return WebSocketAPIWebsocketConnectionRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *WebSocketAPIService) WebsocketConnectionExecute(r WebSocketAPIWebsocketConnectionRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WebSocketAPIService.WebsocketConnection")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/ws"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
