/*
Kenny AGI RDK API

REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

API version: 0.1.0-alpha
Contact: support@kenny-agi.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kennyagi

import (
	"encoding/json"
	"time"
)

// checks if the HealthCheck200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthCheck200Response{}

// HealthCheck200Response struct for HealthCheck200Response
type HealthCheck200Response struct {
	Status *string `json:"status,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Services *HealthCheck200ResponseServices `json:"services,omitempty"`
}

// NewHealthCheck200Response instantiates a new HealthCheck200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthCheck200Response() *HealthCheck200Response {
	this := HealthCheck200Response{}
	return &this
}

// NewHealthCheck200ResponseWithDefaults instantiates a new HealthCheck200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthCheck200ResponseWithDefaults() *HealthCheck200Response {
	this := HealthCheck200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *HealthCheck200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthCheck200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *HealthCheck200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *HealthCheck200Response) SetStatus(v string) {
	o.Status = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *HealthCheck200Response) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthCheck200Response) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *HealthCheck200Response) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *HealthCheck200Response) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *HealthCheck200Response) GetServices() HealthCheck200ResponseServices {
	if o == nil || IsNil(o.Services) {
		var ret HealthCheck200ResponseServices
		return ret
	}
	return *o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthCheck200Response) GetServicesOk() (*HealthCheck200ResponseServices, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *HealthCheck200Response) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given HealthCheck200ResponseServices and assigns it to the Services field.
func (o *HealthCheck200Response) SetServices(v HealthCheck200ResponseServices) {
	o.Services = &v
}

func (o HealthCheck200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthCheck200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	return toSerialize, nil
}

type NullableHealthCheck200Response struct {
	value *HealthCheck200Response
	isSet bool
}

func (v NullableHealthCheck200Response) Get() *HealthCheck200Response {
	return v.value
}

func (v *NullableHealthCheck200Response) Set(val *HealthCheck200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthCheck200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthCheck200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthCheck200Response(val *HealthCheck200Response) *NullableHealthCheck200Response {
	return &NullableHealthCheck200Response{value: val, isSet: true}
}

func (v NullableHealthCheck200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthCheck200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


