/*
Kenny AGI RDK API

REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

API version: 0.1.0-alpha
Contact: support@kenny-agi.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kennyagi

import (
	"encoding/json"
)

// checks if the AGIConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AGIConfigRequest{}

// AGIConfigRequest struct for AGIConfigRequest
type AGIConfigRequest struct {
	// Name identifier for the AGI instance
	Name *string `json:"name,omitempty"`
	// Enable consciousness operations
	ConsciousnessEnabled *bool `json:"consciousness_enabled,omitempty"`
	// Enable safety constraints and monitoring
	SafetyMode *bool `json:"safety_mode,omitempty"`
	// Enable divine mathematics access (requires elevated permissions)
	DivineAccess *bool `json:"divine_access,omitempty"`
	// Enable quantum computing enhancements
	QuantumEnhanced *bool `json:"quantum_enhanced,omitempty"`
}

// NewAGIConfigRequest instantiates a new AGIConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAGIConfigRequest() *AGIConfigRequest {
	this := AGIConfigRequest{}
	var name string = "KennyAGI"
	this.Name = &name
	var consciousnessEnabled bool = true
	this.ConsciousnessEnabled = &consciousnessEnabled
	var safetyMode bool = true
	this.SafetyMode = &safetyMode
	var divineAccess bool = false
	this.DivineAccess = &divineAccess
	var quantumEnhanced bool = false
	this.QuantumEnhanced = &quantumEnhanced
	return &this
}

// NewAGIConfigRequestWithDefaults instantiates a new AGIConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAGIConfigRequestWithDefaults() *AGIConfigRequest {
	this := AGIConfigRequest{}
	var name string = "KennyAGI"
	this.Name = &name
	var consciousnessEnabled bool = true
	this.ConsciousnessEnabled = &consciousnessEnabled
	var safetyMode bool = true
	this.SafetyMode = &safetyMode
	var divineAccess bool = false
	this.DivineAccess = &divineAccess
	var quantumEnhanced bool = false
	this.QuantumEnhanced = &quantumEnhanced
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AGIConfigRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AGIConfigRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AGIConfigRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AGIConfigRequest) SetName(v string) {
	o.Name = &v
}

// GetConsciousnessEnabled returns the ConsciousnessEnabled field value if set, zero value otherwise.
func (o *AGIConfigRequest) GetConsciousnessEnabled() bool {
	if o == nil || IsNil(o.ConsciousnessEnabled) {
		var ret bool
		return ret
	}
	return *o.ConsciousnessEnabled
}

// GetConsciousnessEnabledOk returns a tuple with the ConsciousnessEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AGIConfigRequest) GetConsciousnessEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ConsciousnessEnabled) {
		return nil, false
	}
	return o.ConsciousnessEnabled, true
}

// HasConsciousnessEnabled returns a boolean if a field has been set.
func (o *AGIConfigRequest) HasConsciousnessEnabled() bool {
	if o != nil && !IsNil(o.ConsciousnessEnabled) {
		return true
	}

	return false
}

// SetConsciousnessEnabled gets a reference to the given bool and assigns it to the ConsciousnessEnabled field.
func (o *AGIConfigRequest) SetConsciousnessEnabled(v bool) {
	o.ConsciousnessEnabled = &v
}

// GetSafetyMode returns the SafetyMode field value if set, zero value otherwise.
func (o *AGIConfigRequest) GetSafetyMode() bool {
	if o == nil || IsNil(o.SafetyMode) {
		var ret bool
		return ret
	}
	return *o.SafetyMode
}

// GetSafetyModeOk returns a tuple with the SafetyMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AGIConfigRequest) GetSafetyModeOk() (*bool, bool) {
	if o == nil || IsNil(o.SafetyMode) {
		return nil, false
	}
	return o.SafetyMode, true
}

// HasSafetyMode returns a boolean if a field has been set.
func (o *AGIConfigRequest) HasSafetyMode() bool {
	if o != nil && !IsNil(o.SafetyMode) {
		return true
	}

	return false
}

// SetSafetyMode gets a reference to the given bool and assigns it to the SafetyMode field.
func (o *AGIConfigRequest) SetSafetyMode(v bool) {
	o.SafetyMode = &v
}

// GetDivineAccess returns the DivineAccess field value if set, zero value otherwise.
func (o *AGIConfigRequest) GetDivineAccess() bool {
	if o == nil || IsNil(o.DivineAccess) {
		var ret bool
		return ret
	}
	return *o.DivineAccess
}

// GetDivineAccessOk returns a tuple with the DivineAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AGIConfigRequest) GetDivineAccessOk() (*bool, bool) {
	if o == nil || IsNil(o.DivineAccess) {
		return nil, false
	}
	return o.DivineAccess, true
}

// HasDivineAccess returns a boolean if a field has been set.
func (o *AGIConfigRequest) HasDivineAccess() bool {
	if o != nil && !IsNil(o.DivineAccess) {
		return true
	}

	return false
}

// SetDivineAccess gets a reference to the given bool and assigns it to the DivineAccess field.
func (o *AGIConfigRequest) SetDivineAccess(v bool) {
	o.DivineAccess = &v
}

// GetQuantumEnhanced returns the QuantumEnhanced field value if set, zero value otherwise.
func (o *AGIConfigRequest) GetQuantumEnhanced() bool {
	if o == nil || IsNil(o.QuantumEnhanced) {
		var ret bool
		return ret
	}
	return *o.QuantumEnhanced
}

// GetQuantumEnhancedOk returns a tuple with the QuantumEnhanced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AGIConfigRequest) GetQuantumEnhancedOk() (*bool, bool) {
	if o == nil || IsNil(o.QuantumEnhanced) {
		return nil, false
	}
	return o.QuantumEnhanced, true
}

// HasQuantumEnhanced returns a boolean if a field has been set.
func (o *AGIConfigRequest) HasQuantumEnhanced() bool {
	if o != nil && !IsNil(o.QuantumEnhanced) {
		return true
	}

	return false
}

// SetQuantumEnhanced gets a reference to the given bool and assigns it to the QuantumEnhanced field.
func (o *AGIConfigRequest) SetQuantumEnhanced(v bool) {
	o.QuantumEnhanced = &v
}

func (o AGIConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AGIConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ConsciousnessEnabled) {
		toSerialize["consciousness_enabled"] = o.ConsciousnessEnabled
	}
	if !IsNil(o.SafetyMode) {
		toSerialize["safety_mode"] = o.SafetyMode
	}
	if !IsNil(o.DivineAccess) {
		toSerialize["divine_access"] = o.DivineAccess
	}
	if !IsNil(o.QuantumEnhanced) {
		toSerialize["quantum_enhanced"] = o.QuantumEnhanced
	}
	return toSerialize, nil
}

type NullableAGIConfigRequest struct {
	value *AGIConfigRequest
	isSet bool
}

func (v NullableAGIConfigRequest) Get() *AGIConfigRequest {
	return v.value
}

func (v *NullableAGIConfigRequest) Set(val *AGIConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAGIConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAGIConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAGIConfigRequest(val *AGIConfigRequest) *NullableAGIConfigRequest {
	return &NullableAGIConfigRequest{value: val, isSet: true}
}

func (v NullableAGIConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAGIConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


