/*
Kenny AGI RDK API

REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

API version: 0.1.0-alpha
Contact: support@kenny-agi.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kennyagi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CheckAlignmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckAlignmentRequest{}

// CheckAlignmentRequest struct for CheckAlignmentRequest
type CheckAlignmentRequest struct {
	// The action to check for alignment
	Action string `json:"action"`
}

type _CheckAlignmentRequest CheckAlignmentRequest

// NewCheckAlignmentRequest instantiates a new CheckAlignmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckAlignmentRequest(action string) *CheckAlignmentRequest {
	this := CheckAlignmentRequest{}
	this.Action = action
	return &this
}

// NewCheckAlignmentRequestWithDefaults instantiates a new CheckAlignmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckAlignmentRequestWithDefaults() *CheckAlignmentRequest {
	this := CheckAlignmentRequest{}
	return &this
}

// GetAction returns the Action field value
func (o *CheckAlignmentRequest) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *CheckAlignmentRequest) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *CheckAlignmentRequest) SetAction(v string) {
	o.Action = v
}

func (o CheckAlignmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckAlignmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	return toSerialize, nil
}

func (o *CheckAlignmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckAlignmentRequest := _CheckAlignmentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckAlignmentRequest)

	if err != nil {
		return err
	}

	*o = CheckAlignmentRequest(varCheckAlignmentRequest)

	return err
}

type NullableCheckAlignmentRequest struct {
	value *CheckAlignmentRequest
	isSet bool
}

func (v NullableCheckAlignmentRequest) Get() *CheckAlignmentRequest {
	return v.value
}

func (v *NullableCheckAlignmentRequest) Set(val *CheckAlignmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckAlignmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckAlignmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckAlignmentRequest(val *CheckAlignmentRequest) *NullableCheckAlignmentRequest {
	return &NullableCheckAlignmentRequest{value: val, isSet: true}
}

func (v NullableCheckAlignmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckAlignmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


