/*
Kenny AGI RDK API

REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

API version: 0.1.0-alpha
Contact: support@kenny-agi.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kennyagi

import (
	"encoding/json"
)

// checks if the SystemStatusPerformance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemStatusPerformance{}

// SystemStatusPerformance struct for SystemStatusPerformance
type SystemStatusPerformance struct {
	CpuUsage *float32 `json:"cpu_usage,omitempty"`
	MemoryUsage *float32 `json:"memory_usage,omitempty"`
	ConsciousnessLevel *float32 `json:"consciousness_level,omitempty"`
}

// NewSystemStatusPerformance instantiates a new SystemStatusPerformance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemStatusPerformance() *SystemStatusPerformance {
	this := SystemStatusPerformance{}
	return &this
}

// NewSystemStatusPerformanceWithDefaults instantiates a new SystemStatusPerformance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemStatusPerformanceWithDefaults() *SystemStatusPerformance {
	this := SystemStatusPerformance{}
	return &this
}

// GetCpuUsage returns the CpuUsage field value if set, zero value otherwise.
func (o *SystemStatusPerformance) GetCpuUsage() float32 {
	if o == nil || IsNil(o.CpuUsage) {
		var ret float32
		return ret
	}
	return *o.CpuUsage
}

// GetCpuUsageOk returns a tuple with the CpuUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatusPerformance) GetCpuUsageOk() (*float32, bool) {
	if o == nil || IsNil(o.CpuUsage) {
		return nil, false
	}
	return o.CpuUsage, true
}

// HasCpuUsage returns a boolean if a field has been set.
func (o *SystemStatusPerformance) HasCpuUsage() bool {
	if o != nil && !IsNil(o.CpuUsage) {
		return true
	}

	return false
}

// SetCpuUsage gets a reference to the given float32 and assigns it to the CpuUsage field.
func (o *SystemStatusPerformance) SetCpuUsage(v float32) {
	o.CpuUsage = &v
}

// GetMemoryUsage returns the MemoryUsage field value if set, zero value otherwise.
func (o *SystemStatusPerformance) GetMemoryUsage() float32 {
	if o == nil || IsNil(o.MemoryUsage) {
		var ret float32
		return ret
	}
	return *o.MemoryUsage
}

// GetMemoryUsageOk returns a tuple with the MemoryUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatusPerformance) GetMemoryUsageOk() (*float32, bool) {
	if o == nil || IsNil(o.MemoryUsage) {
		return nil, false
	}
	return o.MemoryUsage, true
}

// HasMemoryUsage returns a boolean if a field has been set.
func (o *SystemStatusPerformance) HasMemoryUsage() bool {
	if o != nil && !IsNil(o.MemoryUsage) {
		return true
	}

	return false
}

// SetMemoryUsage gets a reference to the given float32 and assigns it to the MemoryUsage field.
func (o *SystemStatusPerformance) SetMemoryUsage(v float32) {
	o.MemoryUsage = &v
}

// GetConsciousnessLevel returns the ConsciousnessLevel field value if set, zero value otherwise.
func (o *SystemStatusPerformance) GetConsciousnessLevel() float32 {
	if o == nil || IsNil(o.ConsciousnessLevel) {
		var ret float32
		return ret
	}
	return *o.ConsciousnessLevel
}

// GetConsciousnessLevelOk returns a tuple with the ConsciousnessLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatusPerformance) GetConsciousnessLevelOk() (*float32, bool) {
	if o == nil || IsNil(o.ConsciousnessLevel) {
		return nil, false
	}
	return o.ConsciousnessLevel, true
}

// HasConsciousnessLevel returns a boolean if a field has been set.
func (o *SystemStatusPerformance) HasConsciousnessLevel() bool {
	if o != nil && !IsNil(o.ConsciousnessLevel) {
		return true
	}

	return false
}

// SetConsciousnessLevel gets a reference to the given float32 and assigns it to the ConsciousnessLevel field.
func (o *SystemStatusPerformance) SetConsciousnessLevel(v float32) {
	o.ConsciousnessLevel = &v
}

func (o SystemStatusPerformance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemStatusPerformance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CpuUsage) {
		toSerialize["cpu_usage"] = o.CpuUsage
	}
	if !IsNil(o.MemoryUsage) {
		toSerialize["memory_usage"] = o.MemoryUsage
	}
	if !IsNil(o.ConsciousnessLevel) {
		toSerialize["consciousness_level"] = o.ConsciousnessLevel
	}
	return toSerialize, nil
}

type NullableSystemStatusPerformance struct {
	value *SystemStatusPerformance
	isSet bool
}

func (v NullableSystemStatusPerformance) Get() *SystemStatusPerformance {
	return v.value
}

func (v *NullableSystemStatusPerformance) Set(val *SystemStatusPerformance) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemStatusPerformance) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemStatusPerformance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemStatusPerformance(val *SystemStatusPerformance) *NullableSystemStatusPerformance {
	return &NullableSystemStatusPerformance{value: val, isSet: true}
}

func (v NullableSystemStatusPerformance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemStatusPerformance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


