/*
Kenny AGI RDK API

REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

API version: 0.1.0-alpha
Contact: support@kenny-agi.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kennyagi

import (
	"encoding/json"
)

// checks if the ConsciousnessLevel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsciousnessLevel{}

// ConsciousnessLevel struct for ConsciousnessLevel
type ConsciousnessLevel struct {
	Level *string `json:"level,omitempty"`
	// Numeric consciousness value
	Value *float32 `json:"value,omitempty"`
	// Whether consciousness processing is active
	Active *bool `json:"active,omitempty"`
}

// NewConsciousnessLevel instantiates a new ConsciousnessLevel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsciousnessLevel() *ConsciousnessLevel {
	this := ConsciousnessLevel{}
	return &this
}

// NewConsciousnessLevelWithDefaults instantiates a new ConsciousnessLevel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsciousnessLevelWithDefaults() *ConsciousnessLevel {
	this := ConsciousnessLevel{}
	return &this
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *ConsciousnessLevel) GetLevel() string {
	if o == nil || IsNil(o.Level) {
		var ret string
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsciousnessLevel) GetLevelOk() (*string, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *ConsciousnessLevel) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given string and assigns it to the Level field.
func (o *ConsciousnessLevel) SetLevel(v string) {
	o.Level = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ConsciousnessLevel) GetValue() float32 {
	if o == nil || IsNil(o.Value) {
		var ret float32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsciousnessLevel) GetValueOk() (*float32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ConsciousnessLevel) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float32 and assigns it to the Value field.
func (o *ConsciousnessLevel) SetValue(v float32) {
	o.Value = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *ConsciousnessLevel) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsciousnessLevel) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *ConsciousnessLevel) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *ConsciousnessLevel) SetActive(v bool) {
	o.Active = &v
}

func (o ConsciousnessLevel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsciousnessLevel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	return toSerialize, nil
}

type NullableConsciousnessLevel struct {
	value *ConsciousnessLevel
	isSet bool
}

func (v NullableConsciousnessLevel) Get() *ConsciousnessLevel {
	return v.value
}

func (v *NullableConsciousnessLevel) Set(val *ConsciousnessLevel) {
	v.value = val
	v.isSet = true
}

func (v NullableConsciousnessLevel) IsSet() bool {
	return v.isSet
}

func (v *NullableConsciousnessLevel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsciousnessLevel(val *ConsciousnessLevel) *NullableConsciousnessLevel {
	return &NullableConsciousnessLevel{value: val, isSet: true}
}

func (v NullableConsciousnessLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsciousnessLevel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


