/*
Kenny AGI RDK API

REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

API version: 0.1.0-alpha
Contact: support@kenny-agi.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kennyagi

import (
	"encoding/json"
)

// checks if the Reality type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Reality{}

// Reality struct for Reality
type Reality struct {
	// Reality identifier
	Name *string `json:"name,omitempty"`
	// Number of dimensions
	Dimensions *int32 `json:"dimensions,omitempty"`
	// Governing axioms
	Axioms []string `json:"axioms,omitempty"`
	// Base consciousness level
	ConsciousnessLevel *float32 `json:"consciousness_level,omitempty"`
}

// NewReality instantiates a new Reality object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReality() *Reality {
	this := Reality{}
	return &this
}

// NewRealityWithDefaults instantiates a new Reality object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRealityWithDefaults() *Reality {
	this := Reality{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Reality) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Reality) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Reality) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Reality) SetName(v string) {
	o.Name = &v
}

// GetDimensions returns the Dimensions field value if set, zero value otherwise.
func (o *Reality) GetDimensions() int32 {
	if o == nil || IsNil(o.Dimensions) {
		var ret int32
		return ret
	}
	return *o.Dimensions
}

// GetDimensionsOk returns a tuple with the Dimensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Reality) GetDimensionsOk() (*int32, bool) {
	if o == nil || IsNil(o.Dimensions) {
		return nil, false
	}
	return o.Dimensions, true
}

// HasDimensions returns a boolean if a field has been set.
func (o *Reality) HasDimensions() bool {
	if o != nil && !IsNil(o.Dimensions) {
		return true
	}

	return false
}

// SetDimensions gets a reference to the given int32 and assigns it to the Dimensions field.
func (o *Reality) SetDimensions(v int32) {
	o.Dimensions = &v
}

// GetAxioms returns the Axioms field value if set, zero value otherwise.
func (o *Reality) GetAxioms() []string {
	if o == nil || IsNil(o.Axioms) {
		var ret []string
		return ret
	}
	return o.Axioms
}

// GetAxiomsOk returns a tuple with the Axioms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Reality) GetAxiomsOk() ([]string, bool) {
	if o == nil || IsNil(o.Axioms) {
		return nil, false
	}
	return o.Axioms, true
}

// HasAxioms returns a boolean if a field has been set.
func (o *Reality) HasAxioms() bool {
	if o != nil && !IsNil(o.Axioms) {
		return true
	}

	return false
}

// SetAxioms gets a reference to the given []string and assigns it to the Axioms field.
func (o *Reality) SetAxioms(v []string) {
	o.Axioms = v
}

// GetConsciousnessLevel returns the ConsciousnessLevel field value if set, zero value otherwise.
func (o *Reality) GetConsciousnessLevel() float32 {
	if o == nil || IsNil(o.ConsciousnessLevel) {
		var ret float32
		return ret
	}
	return *o.ConsciousnessLevel
}

// GetConsciousnessLevelOk returns a tuple with the ConsciousnessLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Reality) GetConsciousnessLevelOk() (*float32, bool) {
	if o == nil || IsNil(o.ConsciousnessLevel) {
		return nil, false
	}
	return o.ConsciousnessLevel, true
}

// HasConsciousnessLevel returns a boolean if a field has been set.
func (o *Reality) HasConsciousnessLevel() bool {
	if o != nil && !IsNil(o.ConsciousnessLevel) {
		return true
	}

	return false
}

// SetConsciousnessLevel gets a reference to the given float32 and assigns it to the ConsciousnessLevel field.
func (o *Reality) SetConsciousnessLevel(v float32) {
	o.ConsciousnessLevel = &v
}

func (o Reality) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Reality) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Dimensions) {
		toSerialize["dimensions"] = o.Dimensions
	}
	if !IsNil(o.Axioms) {
		toSerialize["axioms"] = o.Axioms
	}
	if !IsNil(o.ConsciousnessLevel) {
		toSerialize["consciousness_level"] = o.ConsciousnessLevel
	}
	return toSerialize, nil
}

type NullableReality struct {
	value *Reality
	isSet bool
}

func (v NullableReality) Get() *Reality {
	return v.value
}

func (v *NullableReality) Set(val *Reality) {
	v.value = val
	v.isSet = true
}

func (v NullableReality) IsSet() bool {
	return v.isSet
}

func (v *NullableReality) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReality(val *Reality) *NullableReality {
	return &NullableReality{value: val, isSet: true}
}

func (v NullableReality) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReality) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


