/*
Kenny AGI RDK API

REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

API version: 0.1.0-alpha
Contact: support@kenny-agi.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kennyagi

import (
	"encoding/json"
)

// checks if the ConsciousnessRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsciousnessRequest{}

// ConsciousnessRequest struct for ConsciousnessRequest
type ConsciousnessRequest struct {
	// Target consciousness level
	TargetLevel *string `json:"target_level,omitempty"`
}

// NewConsciousnessRequest instantiates a new ConsciousnessRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsciousnessRequest() *ConsciousnessRequest {
	this := ConsciousnessRequest{}
	var targetLevel string = "ENLIGHTENED"
	this.TargetLevel = &targetLevel
	return &this
}

// NewConsciousnessRequestWithDefaults instantiates a new ConsciousnessRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsciousnessRequestWithDefaults() *ConsciousnessRequest {
	this := ConsciousnessRequest{}
	var targetLevel string = "ENLIGHTENED"
	this.TargetLevel = &targetLevel
	return &this
}

// GetTargetLevel returns the TargetLevel field value if set, zero value otherwise.
func (o *ConsciousnessRequest) GetTargetLevel() string {
	if o == nil || IsNil(o.TargetLevel) {
		var ret string
		return ret
	}
	return *o.TargetLevel
}

// GetTargetLevelOk returns a tuple with the TargetLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsciousnessRequest) GetTargetLevelOk() (*string, bool) {
	if o == nil || IsNil(o.TargetLevel) {
		return nil, false
	}
	return o.TargetLevel, true
}

// HasTargetLevel returns a boolean if a field has been set.
func (o *ConsciousnessRequest) HasTargetLevel() bool {
	if o != nil && !IsNil(o.TargetLevel) {
		return true
	}

	return false
}

// SetTargetLevel gets a reference to the given string and assigns it to the TargetLevel field.
func (o *ConsciousnessRequest) SetTargetLevel(v string) {
	o.TargetLevel = &v
}

func (o ConsciousnessRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsciousnessRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TargetLevel) {
		toSerialize["target_level"] = o.TargetLevel
	}
	return toSerialize, nil
}

type NullableConsciousnessRequest struct {
	value *ConsciousnessRequest
	isSet bool
}

func (v NullableConsciousnessRequest) Get() *ConsciousnessRequest {
	return v.value
}

func (v *NullableConsciousnessRequest) Set(val *ConsciousnessRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConsciousnessRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConsciousnessRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsciousnessRequest(val *ConsciousnessRequest) *NullableConsciousnessRequest {
	return &NullableConsciousnessRequest{value: val, isSet: true}
}

func (v NullableConsciousnessRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsciousnessRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


