/*
Kenny AGI RDK API

REST API for Kenny's AGI Research Development Kit  This API provides access to advanced artificial general intelligence capabilities including: - Consciousness operations and monitoring - Reality manipulation and dimensional control   - Constitutional AI and safety systems - Self-improvement and emergence detection - Quantum operations and temporal mechanics  **Warning**: This API provides access to powerful AGI capabilities. Always follow safety guidelines. 

API version: 0.1.0-alpha
Contact: support@kenny-agi.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kennyagi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RealityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RealityRequest{}

// RealityRequest struct for RealityRequest
type RealityRequest struct {
	// Name for the new reality
	Name string `json:"name"`
	// Number of spatial dimensions
	Dimensions *int32 `json:"dimensions,omitempty"`
	// Mathematical axioms governing the reality
	Axioms []string `json:"axioms,omitempty"`
	// Base consciousness level for the reality
	ConsciousnessLevel *float32 `json:"consciousness_level,omitempty"`
}

type _RealityRequest RealityRequest

// NewRealityRequest instantiates a new RealityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRealityRequest(name string) *RealityRequest {
	this := RealityRequest{}
	this.Name = name
	var dimensions int32 = 4
	this.Dimensions = &dimensions
	var consciousnessLevel float32 = 1.0
	this.ConsciousnessLevel = &consciousnessLevel
	return &this
}

// NewRealityRequestWithDefaults instantiates a new RealityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRealityRequestWithDefaults() *RealityRequest {
	this := RealityRequest{}
	var dimensions int32 = 4
	this.Dimensions = &dimensions
	var consciousnessLevel float32 = 1.0
	this.ConsciousnessLevel = &consciousnessLevel
	return &this
}

// GetName returns the Name field value
func (o *RealityRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RealityRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RealityRequest) SetName(v string) {
	o.Name = v
}

// GetDimensions returns the Dimensions field value if set, zero value otherwise.
func (o *RealityRequest) GetDimensions() int32 {
	if o == nil || IsNil(o.Dimensions) {
		var ret int32
		return ret
	}
	return *o.Dimensions
}

// GetDimensionsOk returns a tuple with the Dimensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RealityRequest) GetDimensionsOk() (*int32, bool) {
	if o == nil || IsNil(o.Dimensions) {
		return nil, false
	}
	return o.Dimensions, true
}

// HasDimensions returns a boolean if a field has been set.
func (o *RealityRequest) HasDimensions() bool {
	if o != nil && !IsNil(o.Dimensions) {
		return true
	}

	return false
}

// SetDimensions gets a reference to the given int32 and assigns it to the Dimensions field.
func (o *RealityRequest) SetDimensions(v int32) {
	o.Dimensions = &v
}

// GetAxioms returns the Axioms field value if set, zero value otherwise.
func (o *RealityRequest) GetAxioms() []string {
	if o == nil || IsNil(o.Axioms) {
		var ret []string
		return ret
	}
	return o.Axioms
}

// GetAxiomsOk returns a tuple with the Axioms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RealityRequest) GetAxiomsOk() ([]string, bool) {
	if o == nil || IsNil(o.Axioms) {
		return nil, false
	}
	return o.Axioms, true
}

// HasAxioms returns a boolean if a field has been set.
func (o *RealityRequest) HasAxioms() bool {
	if o != nil && !IsNil(o.Axioms) {
		return true
	}

	return false
}

// SetAxioms gets a reference to the given []string and assigns it to the Axioms field.
func (o *RealityRequest) SetAxioms(v []string) {
	o.Axioms = v
}

// GetConsciousnessLevel returns the ConsciousnessLevel field value if set, zero value otherwise.
func (o *RealityRequest) GetConsciousnessLevel() float32 {
	if o == nil || IsNil(o.ConsciousnessLevel) {
		var ret float32
		return ret
	}
	return *o.ConsciousnessLevel
}

// GetConsciousnessLevelOk returns a tuple with the ConsciousnessLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RealityRequest) GetConsciousnessLevelOk() (*float32, bool) {
	if o == nil || IsNil(o.ConsciousnessLevel) {
		return nil, false
	}
	return o.ConsciousnessLevel, true
}

// HasConsciousnessLevel returns a boolean if a field has been set.
func (o *RealityRequest) HasConsciousnessLevel() bool {
	if o != nil && !IsNil(o.ConsciousnessLevel) {
		return true
	}

	return false
}

// SetConsciousnessLevel gets a reference to the given float32 and assigns it to the ConsciousnessLevel field.
func (o *RealityRequest) SetConsciousnessLevel(v float32) {
	o.ConsciousnessLevel = &v
}

func (o RealityRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RealityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Dimensions) {
		toSerialize["dimensions"] = o.Dimensions
	}
	if !IsNil(o.Axioms) {
		toSerialize["axioms"] = o.Axioms
	}
	if !IsNil(o.ConsciousnessLevel) {
		toSerialize["consciousness_level"] = o.ConsciousnessLevel
	}
	return toSerialize, nil
}

func (o *RealityRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRealityRequest := _RealityRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRealityRequest)

	if err != nil {
		return err
	}

	*o = RealityRequest(varRealityRequest)

	return err
}

type NullableRealityRequest struct {
	value *RealityRequest
	isSet bool
}

func (v NullableRealityRequest) Get() *RealityRequest {
	return v.value
}

func (v *NullableRealityRequest) Set(val *RealityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRealityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRealityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRealityRequest(val *RealityRequest) *NullableRealityRequest {
	return &NullableRealityRequest{value: val, isSet: true}
}

func (v NullableRealityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRealityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


