#!/usr/bin/env python3
"""
LIVE DEPLOYMENT: HuggingFace Model to CUDO Compute
This script ACTUALLY provisions a GPU and deploys a model
WARNING: This will incur real costs!
"""

import json
import requests
import time
import sys
from datetime import datetime

# CUDO Configuration
API_KEY = "a661306311d02d22e5a35f02b14ab2203b856906b326d029867a6733530860d0"
BASE_URL = "https://rest.compute.cudo.org"
PROJECT_ID = "kenny"

def create_vm_with_huggingface(model_name="distilgpt2", dry_run=True):
    """
    Create a CUDO VM with HuggingFace model deployment
    
    Args:
        model_name: HuggingFace model to deploy
        dry_run: If True, only show config without creating VM
    """
    
    print("=" * 80)
    print("🚀 HUGGINGFACE → CUDO DEPLOYMENT")
    print("=" * 80)
    print(f"Model: {model_name}")
    print(f"Project: {PROJECT_ID}")
    print(f"Mode: {'DRY RUN' if dry_run else '⚠️ LIVE DEPLOYMENT'}")
    print()
    
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json",
        "Accept": "application/json"
    }
    
    # VM Configuration for HuggingFace deployment
    vm_config = {
        "machineType": "epyc-milan-rtx-a5000",  # RTX A5000 - cheapest GPU
        "dataCenterId": "no-luster-1",  # Norway data center
        "bootDiskSizeGib": 100,
        "memoryGib": 32,
        "vcpus": 8,
        "gpus": 1,
        "id": f"hf-{model_name.replace('/', '-')}-{int(time.time())}",
        "sshKeyIds": [],
        "metadata": {
            "startup-script": f"""#!/bin/bash
# CUDO HuggingFace Model Deployment Script
# Model: {model_name}
# Generated by Kenny MLOps Team

echo "Starting HuggingFace deployment..." | tee /var/log/deployment.log

# Update system
apt-get update && apt-get install -y python3-pip git curl wget | tee -a /var/log/deployment.log

# Install CUDA drivers if needed
if ! nvidia-smi; then
    wget https://developer.download.nvidia.com/compute/cuda/12.0.0/local_installers/cuda_12.0.0_525.60.13_linux.run
    sh cuda_12.0.0_525.60.13_linux.run --silent --driver
fi

# Install Python packages
pip3 install --upgrade pip | tee -a /var/log/deployment.log
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 | tee -a /var/log/deployment.log
pip3 install transformers accelerate huggingface-hub datasets fastapi uvicorn | tee -a /var/log/deployment.log

# Download the model
python3 -c "
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

print('Downloading model: {model_name}')
model = AutoModelForCausalLM.from_pretrained('{model_name}')
tokenizer = AutoTokenizer.from_pretrained('{model_name}')
print('Model downloaded successfully!')

# Save model info
import json
info = {{
    'model': '{model_name}',
    'downloaded_at': '$(date)',
    'gpu': 'RTX A5000',
    'deployment': 'CUDO Compute'
}}
with open('/opt/model_info.json', 'w') as f:
    json.dump(info, f)
" | tee -a /var/log/deployment.log

# Create FastAPI server
cat > /opt/model_server.py << 'SERVEREOF'
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from transformers import pipeline
import torch
import uvicorn
import json

app = FastAPI(title="HuggingFace Model on CUDO")

# Load model
print("Loading model...")
device = 0 if torch.cuda.is_available() else -1
generator = pipeline('text-generation', model='{model_name}', device=device)

class GenerateRequest(BaseModel):
    prompt: str
    max_length: int = 100
    temperature: float = 0.7

class GenerateResponse(BaseModel):
    generated_text: str
    model: str = '{model_name}'
    gpu: str = 'RTX A5000'
    device: str = 'cuda' if torch.cuda.is_available() else 'cpu'

@app.get("/")
def root():
    return {{
        "status": "running",
        "model": "{model_name}",
        "gpu": "RTX A5000",
        "provider": "CUDO Compute",
        "deployed_by": "Kenny MLOps Team"
    }}

@app.post("/generate", response_model=GenerateResponse)
async def generate(request: GenerateRequest):
    try:
        result = generator(
            request.prompt,
            max_length=request.max_length,
            temperature=request.temperature,
            do_sample=True
        )
        return GenerateResponse(generated_text=result[0]['generated_text'])
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/health")
def health():
    return {{"status": "healthy", "cuda": torch.cuda.is_available()}}

if __name__ == "__main__":
    print(f"GPU Available: {{torch.cuda.is_available()}}")
    if torch.cuda.is_available():
        print(f"GPU Name: {{torch.cuda.get_device_name(0)}}")
    uvicorn.run(app, host="0.0.0.0", port=8000)
SERVEREOF

# Start the model server
nohup python3 /opt/model_server.py > /var/log/model_server.log 2>&1 &

# Create a simple status page
cat > /var/www/html/index.html << 'EOF'
<!DOCTYPE html>
<html>
<head><title>HuggingFace on CUDO</title></head>
<body>
<h1>🚀 Model Deployed Successfully!</h1>
<p>Model: {model_name}</p>
<p>GPU: RTX A5000</p>
<p>API Endpoint: http://[VM_IP]:8000</p>
<p>Deployed by: Kenny MLOps Team</p>
</body>
</html>
EOF

echo "Deployment complete!" | tee -a /var/log/deployment.log
echo "Model server running on port 8000" | tee -a /var/log/deployment.log
"""
        },
        "tags": ["huggingface", "mlops", "kenny", model_name.replace("/", "-")]
    }
    
    print("📋 VM Configuration:")
    print(f"  Machine Type: {vm_config['machineType']}")
    print(f"  Data Center: {vm_config['dataCenterId']}")
    print(f"  GPU: RTX A5000 (1x)")
    print(f"  Memory: {vm_config['memoryGib']}GB")
    print(f"  vCPUs: {vm_config['vcpus']}")
    print(f"  Disk: {vm_config['bootDiskSizeGib']}GB")
    print(f"  VM ID: {vm_config['id']}")
    print()
    
    print("💰 Estimated Costs:")
    print(f"  GPU: $0.36/hour")
    print(f"  Total: ~$0.50/hour (including compute/storage)")
    print(f"  Daily: ~$12.00")
    print(f"  With scale-to-zero (95% idle): ~$0.60/day")
    print()
    
    if dry_run:
        print("✅ DRY RUN COMPLETE - No VM created")
        print("\nTo actually deploy, run:")
        print(f'  python3 {__file__} --deploy')
        return None
    
    # ACTUAL DEPLOYMENT
    print("⚠️  CREATING REAL VM - This will incur costs!")
    print("Creating VM...")
    
    create_url = f"{BASE_URL}/v1/projects/{PROJECT_ID}/vms"
    
    try:
        response = requests.post(
            create_url,
            headers=headers,
            json=vm_config,
            timeout=30
        )
        
        print(f"Response Status: {response.status_code}")
        
        if response.status_code in [200, 201, 202]:
            vm_data = response.json()
            vm_id = vm_data.get("id", vm_config["id"])
            
            print(f"✅ VM CREATED SUCCESSFULLY!")
            print(f"   VM ID: {vm_id}")
            print(f"   Status: {vm_data.get('status', 'creating')}")
            
            # Wait for VM to be ready
            print("\n⏳ Waiting for VM to be ready...")
            for i in range(30):  # Wait up to 5 minutes
                time.sleep(10)
                
                # Check VM status
                status_response = requests.get(
                    f"{BASE_URL}/v1/projects/{PROJECT_ID}/vms/{vm_id}",
                    headers=headers
                )
                
                if status_response.status_code == 200:
                    vm_info = status_response.json()
                    status = vm_info.get("status", "unknown")
                    print(f"   Status: {status}")
                    
                    if status == "running":
                        ip = vm_info.get("publicIp", "pending")
                        print(f"\n🎉 VM IS RUNNING!")
                        print(f"   Public IP: {ip}")
                        print(f"   Model API: http://{ip}:8000")
                        print(f"   Health Check: http://{ip}:8000/health")
                        print(f"\n📊 Next Steps:")
                        print(f"   1. Wait 2-3 minutes for model to download")
                        print(f"   2. Test API: curl http://{ip}:8000/health")
                        print(f"   3. Generate text: curl -X POST http://{ip}:8000/generate \\")
                        print(f'        -H "Content-Type: application/json" \\')
                        print(f'        -d \'{{"prompt": "Hello, I am", "max_length": 50}}\'')
                        print(f"\n⚠️  REMEMBER TO DELETE VM WHEN DONE!")
                        print(f"   curl -X DELETE {BASE_URL}/v1/projects/{PROJECT_ID}/vms/{vm_id} \\")
                        print(f"     -H 'Authorization: Bearer {API_KEY[:10]}...'")
                        return vm_info
                    
                    elif status in ["failed", "terminated"]:
                        print(f"❌ VM failed to start: {status}")
                        return None
                
                print(".", end="", flush=True)
            
            print("\n⚠️ VM creation timed out - check CUDO dashboard")
            
        else:
            print(f"❌ Failed to create VM: {response.status_code}")
            print(f"Response: {response.text[:500]}")
            
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        
    return None

def list_vms():
    """List all VMs in the project"""
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Accept": "application/json"
    }
    
    response = requests.get(
        f"{BASE_URL}/v1/projects/{PROJECT_ID}/vms",
        headers=headers
    )
    
    if response.status_code == 200:
        data = response.json()
        vms = data.get("VMs", [])
        
        if vms:
            print("\n📋 Active VMs in Kenny project:")
            for vm in vms:
                print(f"  • {vm.get('id')}")
                print(f"    Status: {vm.get('status')}")
                print(f"    IP: {vm.get('publicIp', 'N/A')}")
                print(f"    Created: {vm.get('createTime')}")
        else:
            print("\n✅ No active VMs (no costs)")
    
    return response.json()

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Deploy HuggingFace model to CUDO")
    parser.add_argument("--deploy", action="store_true", help="Actually create VM (costs money!)")
    parser.add_argument("--model", default="distilgpt2", help="HuggingFace model to deploy")
    parser.add_argument("--list", action="store_true", help="List active VMs")
    
    args = parser.parse_args()
    
    if args.list:
        list_vms()
    else:
        result = create_vm_with_huggingface(
            model_name=args.model,
            dry_run=not args.deploy
        )
        
        if not args.deploy:
            print("\n" + "=" * 80)
            print("💡 This was a DRY RUN - no VM was created")
            print("To actually deploy and incur costs, add --deploy flag")
            print("=" * 80)