"""
Integrated Information Theory (IIT) Implementation
=================================================

Implementation of Giulio Tononi's Integrated Information Theory for measuring
consciousness through the computation of Φ (phi) - the amount of integrated
information generated by a system.

Key concepts:
- Integration: Information that is unified across the system
- Differentiation: Information that distinguishes different states
- Exclusion: Information that is intrinsic to the system
- Intrinsic existence: Information from the system's own perspective

Mathematical foundation based on IIT 3.0 framework.
"""

import logging
from dataclasses import dataclass
from itertools import combinations, product
from typing import Dict, List, Optional, Tuple, Union

import networkx as nx
import numpy as np
import torch
from scipy.linalg import eigh
from scipy.spatial.distance import pdist, squareform


@dataclass
class PhiComplex:
    """A complex in IIT - a subset of elements with non-zero Φ."""

    elements: List[int]
    phi_value: float
    mechanism: torch.Tensor
    cause_repertoire: torch.Tensor
    effect_repertoire: torch.Tensor


@dataclass
class ConceptualStructure:
    """Complete conceptual structure of a system."""

    concepts: List[PhiComplex]
    big_phi: float  # System-level Φ
    major_complex: Optional[PhiComplex]


class IITCalculator:
    """
    Integrated Information Theory calculator for measuring consciousness.

    Implements IIT 3.0 framework for computing Φ (integrated information)
    at both mechanism and system levels.
    """

    def __init__(self, device: str = "cuda" if torch.cuda.is_available() else "cpu"):
        """
        Initialize IIT calculator.

        Args:
            device: Computing device for tensor operations
        """
        self.device = device
        self.logger = logging.getLogger(__name__)

        # IIT computation parameters
        self.phi_threshold = 1e-6  # Minimum Φ to consider non-zero
        self.max_subset_size = 8  # Maximum subset size for tractable computation
        self.perturbation_strength = 0.1

    def compute_phi(
        self,
        neural_activations: torch.Tensor,
        connectivity_matrix: Optional[torch.Tensor] = None,
        temporal_window: int = 3,
    ) -> float:
        """
        Compute system-level Φ (big phi) for neural activations.

        Args:
            neural_activations: Neural network activations [batch, time, neurons]
            connectivity_matrix: Optional connectivity weights [neurons, neurons]
            temporal_window: Temporal window for integration analysis

        Returns:
            System-level Φ value representing integrated information
        """
        self.logger.info("Computing integrated information (Φ)")

        try:
            # Ensure proper tensor format
            if neural_activations.dim() == 2:
                neural_activations = neural_activations.unsqueeze(0)  # Add batch dimension

            batch_size, seq_len, num_neurons = neural_activations.shape

            # Extract representative time window
            if seq_len >= temporal_window:
                activations = neural_activations[:, -temporal_window:, :].to(self.device)
            else:
                activations = neural_activations.to(self.device)

            # Infer connectivity if not provided
            if connectivity_matrix is None:
                connectivity_matrix = self._infer_connectivity(activations)

            # Compute Φ for the system
            conceptual_structure = self._compute_conceptual_structure(
                activations, connectivity_matrix
            )

            big_phi = conceptual_structure.big_phi

            self.logger.info(f"Computed Φ = {big_phi:.6f}")
            return float(big_phi)

        except Exception as e:
            self.logger.error(f"Failed to compute Φ: {e}")
            return 0.0

    def _infer_connectivity(self, activations: torch.Tensor) -> torch.Tensor:
        """
        Infer functional connectivity from neural activations.

        Args:
            activations: Neural activations [batch, time, neurons]

        Returns:
            Inferred connectivity matrix [neurons, neurons]
        """
        batch_size, seq_len, num_neurons = activations.shape

        # Flatten across batch and time for correlation analysis
        flattened = activations.reshape(-1, num_neurons)  # [batch*time, neurons]

        # Compute pairwise correlations
        correlations = torch.corrcoef(flattened.T)  # [neurons, neurons]

        # Handle NaN values (can occur with constant activations)
        correlations = torch.nan_to_num(correlations, nan=0.0)

        # Apply threshold and normalization
        threshold = 0.1
        connectivity = torch.where(
            torch.abs(correlations) > threshold, correlations, torch.zeros_like(correlations)
        )

        return connectivity

    def _compute_conceptual_structure(
        self, activations: torch.Tensor, connectivity: torch.Tensor
    ) -> ConceptualStructure:
        """
        Compute the conceptual structure of the system.

        Args:
            activations: Neural activations
            connectivity: Connectivity matrix

        Returns:
            Complete conceptual structure with Φ values
        """
        batch_size, seq_len, num_neurons = activations.shape

        # Limit neurons for tractable computation
        if num_neurons > self.max_subset_size:
            # Select most active neurons
            activity_scores = torch.mean(torch.abs(activations), dim=(0, 1))
            _, top_indices = torch.topk(activity_scores, self.max_subset_size)
            selected_neurons = sorted(top_indices.cpu().tolist())

            activations = activations[:, :, selected_neurons]
            connectivity = connectivity[selected_neurons, :][:, selected_neurons]
            num_neurons = len(selected_neurons)
        else:
            selected_neurons = list(range(num_neurons))

        # Find all possible complexes (subsets of neurons)
        concepts = []
        max_phi = 0.0
        major_complex = None

        # Test subsets of different sizes
        for subset_size in range(1, min(num_neurons + 1, self.max_subset_size + 1)):
            for subset in combinations(range(num_neurons), subset_size):
                subset = list(subset)

                # Compute Φ for this subset
                phi_complex = self._compute_phi_complex(activations, connectivity, subset)

                if phi_complex.phi_value > self.phi_threshold:
                    concepts.append(phi_complex)

                    # Track major complex (highest Φ)
                    if phi_complex.phi_value > max_phi:
                        max_phi = phi_complex.phi_value
                        major_complex = phi_complex

        # System-level Φ is the Φ of the major complex
        big_phi = max_phi

        return ConceptualStructure(concepts=concepts, big_phi=big_phi, major_complex=major_complex)

    def _compute_phi_complex(
        self, activations: torch.Tensor, connectivity: torch.Tensor, subset: List[int]
    ) -> PhiComplex:
        """
        Compute Φ for a specific complex (subset of neurons).

        Args:
            activations: Neural activations
            connectivity: Connectivity matrix
            subset: Indices of neurons in the complex

        Returns:
            PhiComplex with computed Φ value
        """
        if len(subset) == 1:
            # Single neuron - compute intrinsic information
            phi_value = self._compute_intrinsic_information(
                activations[:, :, subset], connectivity[subset, :][:, subset]
            )
        else:
            # Multi-neuron complex - compute integration
            phi_value = self._compute_integrated_information(
                activations[:, :, subset], connectivity[subset, :][:, subset]
            )

        # Create mechanism representation
        mechanism = activations[:, -1, subset].mean(dim=0)  # Latest state

        # Compute cause and effect repertoires (simplified)
        cause_repertoire = self._compute_cause_repertoire(
            activations[:, :, subset], connectivity[subset, :][:, subset]
        )
        effect_repertoire = self._compute_effect_repertoire(
            activations[:, :, subset], connectivity[subset, :][:, subset]
        )

        return PhiComplex(
            elements=subset,
            phi_value=phi_value,
            mechanism=mechanism,
            cause_repertoire=cause_repertoire,
            effect_repertoire=effect_repertoire,
        )

    def _compute_intrinsic_information(
        self, activations: torch.Tensor, connectivity: torch.Tensor
    ) -> float:
        """
        Compute intrinsic information for a single element.

        Args:
            activations: Single neuron activations [batch, time, 1]
            connectivity: Self-connection weight [1, 1]

        Returns:
            Intrinsic information value
        """
        # Measure predictive information - how much the past predicts the future
        if activations.shape[1] < 2:
            return 0.0

        past_states = activations[:, :-1, 0]  # [batch, time-1]
        future_states = activations[:, 1:, 0]  # [batch, time-1]

        # Compute mutual information between past and future
        mi = self._compute_mutual_information(past_states, future_states)

        return float(mi)

    def _compute_integrated_information(
        self, activations: torch.Tensor, connectivity: torch.Tensor
    ) -> float:
        """
        Compute integrated information for a multi-element complex.

        Args:
            activations: Complex activations [batch, time, subset_size]
            connectivity: Subset connectivity matrix

        Returns:
            Integrated information (Φ) value
        """
        if activations.shape[2] < 2:
            return self._compute_intrinsic_information(activations, connectivity)

        # Compute integrated information as difference between:
        # 1. Information of the whole complex
        # 2. Sum of information of minimum information partition (MIP)

        whole_info = self._compute_system_information(activations, connectivity)
        mip_info = self._compute_mip_information(activations, connectivity)

        phi = max(0.0, whole_info - mip_info)

        return phi

    def _compute_system_information(
        self, activations: torch.Tensor, connectivity: torch.Tensor
    ) -> float:
        """Compute total system information."""
        batch_size, seq_len, subset_size = activations.shape

        if seq_len < 2:
            return 0.0

        # Flatten temporal dynamics
        past_states = activations[:, :-1, :].reshape(-1, subset_size)  # [batch*(time-1), subset]
        future_states = activations[:, 1:, :].reshape(-1, subset_size)  # [batch*(time-1), subset]

        # Compute system-level predictive information
        system_mi = 0.0

        # Average mutual information across all element pairs
        for i in range(subset_size):
            for j in range(subset_size):
                if i != j:
                    mi_ij = self._compute_mutual_information(past_states[:, i], future_states[:, j])
                    system_mi += mi_ij

        # Normalize by number of pairs
        if subset_size > 1:
            system_mi /= subset_size * (subset_size - 1)

        return system_mi

    def _compute_mip_information(
        self, activations: torch.Tensor, connectivity: torch.Tensor
    ) -> float:
        """
        Compute information of minimum information partition (MIP).

        This finds the partition that minimizes the information,
        representing the least integrated way to divide the system.
        """
        subset_size = activations.shape[2]

        if subset_size < 2:
            return 0.0

        min_partition_info = float("inf")

        # Try all possible binary partitions
        for partition_size in range(1, subset_size):
            for partition_a in combinations(range(subset_size), partition_size):
                partition_a = list(partition_a)
                partition_b = [i for i in range(subset_size) if i not in partition_a]

                # Compute information for each partition separately
                if len(partition_a) > 0:
                    info_a = self._compute_system_information(
                        activations[:, :, partition_a], connectivity[partition_a, :][:, partition_a]
                    )
                else:
                    info_a = 0.0

                if len(partition_b) > 0:
                    info_b = self._compute_system_information(
                        activations[:, :, partition_b], connectivity[partition_b, :][:, partition_b]
                    )
                else:
                    info_b = 0.0

                # Total partitioned information
                partition_info = info_a + info_b

                # Track minimum
                min_partition_info = min(min_partition_info, partition_info)

        return min_partition_info if min_partition_info != float("inf") else 0.0

    def _compute_mutual_information(self, x: torch.Tensor, y: torch.Tensor) -> float:
        """
        Compute mutual information between two variables.

        Args:
            x: First variable [samples]
            y: Second variable [samples]

        Returns:
            Mutual information estimate
        """
        if len(x) != len(y) or len(x) < 10:
            return 0.0

        try:
            # Convert to numpy for histogram computation
            x_np = x.detach().cpu().numpy()
            y_np = y.detach().cpu().numpy()

            # Discretize continuous values for histogram
            bins = min(10, int(np.sqrt(len(x_np))))

            # Joint histogram
            joint_hist, x_edges, y_edges = np.histogram2d(x_np, y_np, bins=bins)
            joint_hist = joint_hist + 1e-10  # Avoid log(0)

            # Marginal histograms
            x_hist = np.sum(joint_hist, axis=1)
            y_hist = np.sum(joint_hist, axis=0)

            # Normalize to probabilities
            joint_prob = joint_hist / np.sum(joint_hist)
            x_prob = x_hist / np.sum(x_hist)
            y_prob = y_hist / np.sum(y_hist)

            # Compute mutual information
            mi = 0.0
            for i in range(len(x_prob)):
                for j in range(len(y_prob)):
                    if joint_prob[i, j] > 0 and x_prob[i] > 0 and y_prob[j] > 0:
                        mi += joint_prob[i, j] * np.log2(joint_prob[i, j] / (x_prob[i] * y_prob[j]))

            return max(0.0, mi)

        except Exception as e:
            self.logger.warning(f"MI computation failed: {e}")
            return 0.0

    def _compute_cause_repertoire(
        self, activations: torch.Tensor, connectivity: torch.Tensor
    ) -> torch.Tensor:
        """
        Compute cause repertoire - probability distribution over past states.

        Args:
            activations: Neural activations
            connectivity: Connectivity matrix

        Returns:
            Cause repertoire tensor
        """
        if activations.shape[1] < 2:
            return torch.zeros(1, device=self.device)

        # Current state
        current_state = activations[:, -1, :].mean(dim=0)  # Average across batches

        # Past states that could have caused current state
        past_states = activations[:, :-1, :].mean(dim=0)  # [time-1, neurons]

        # Compute weighted influence of past on current
        influence = torch.matmul(past_states, connectivity)  # [time-1, neurons]

        # Similarity to current state
        similarities = torch.cosine_similarity(influence, current_state.unsqueeze(0), dim=1)

        # Convert to probability distribution
        cause_repertoire = torch.softmax(similarities, dim=0)

        return cause_repertoire

    def _compute_effect_repertoire(
        self, activations: torch.Tensor, connectivity: torch.Tensor
    ) -> torch.Tensor:
        """
        Compute effect repertoire - probability distribution over future states.

        Args:
            activations: Neural activations
            connectivity: Connectivity matrix

        Returns:
            Effect repertoire tensor
        """
        if activations.shape[1] < 2:
            return torch.zeros(1, device=self.device)

        # Current state
        current_state = activations[:, -1, :].mean(dim=0)  # Average across batches

        # Predicted future influence
        future_influence = torch.matmul(current_state, connectivity)  # [neurons]

        # Create probability distribution over possible future states
        # Simplified: assume future states distributed around predicted influence
        effect_repertoire = torch.softmax(future_influence, dim=0)

        return effect_repertoire

    def analyze_phi_dynamics(self, activations_sequence: List[torch.Tensor]) -> Dict[str, float]:
        """
        Analyze Φ dynamics over a sequence of activation states.

        Args:
            activations_sequence: List of activation tensors over time

        Returns:
            Dictionary with Φ dynamics analysis
        """
        phi_values = []

        for activations in activations_sequence:
            phi = self.compute_phi(activations)
            phi_values.append(phi)

        phi_array = np.array(phi_values)

        return {
            "mean_phi": float(np.mean(phi_array)),
            "std_phi": float(np.std(phi_array)),
            "max_phi": float(np.max(phi_array)),
            "min_phi": float(np.min(phi_array)),
            "phi_trend": (
                float(np.polyfit(range(len(phi_values)), phi_values, 1)[0])
                if len(phi_values) > 1
                else 0.0
            ),
            "phi_stability": float(1.0 / (1.0 + np.std(phi_array))) if len(phi_array) > 0 else 0.0,
        }

    def compute_phi_spectrum(
        self, neural_activations: torch.Tensor, frequency_bands: List[Tuple[float, float]]
    ) -> Dict[str, float]:
        """
        Compute Φ across different frequency bands.

        Args:
            neural_activations: Neural activations
            frequency_bands: List of (min_freq, max_freq) tuples

        Returns:
            Φ values for each frequency band
        """
        spectrum = {}

        try:
            # Apply FFT to get frequency domain representation
            fft_activations = torch.fft.fft(neural_activations, dim=1)
            freq_magnitude = torch.abs(fft_activations)

            seq_len = neural_activations.shape[1]
            freqs = torch.fft.fftfreq(seq_len, d=1.0)

            for i, (min_freq, max_freq) in enumerate(frequency_bands):
                # Filter to frequency band
                freq_mask = (torch.abs(freqs) >= min_freq) & (torch.abs(freqs) <= max_freq)

                if torch.sum(freq_mask) > 0:
                    # Extract frequency band activations
                    band_fft = fft_activations.clone()
                    band_fft[:, ~freq_mask, :] = 0

                    # Convert back to time domain
                    band_activations = torch.real(torch.fft.ifft(band_fft, dim=1))

                    # Compute Φ for this band
                    band_phi = self.compute_phi(band_activations)
                    spectrum[f"band_{min_freq}_{max_freq}Hz"] = band_phi
                else:
                    spectrum[f"band_{min_freq}_{max_freq}Hz"] = 0.0

        except Exception as e:
            self.logger.error(f"Phi spectrum computation failed: {e}")
            for i, (min_freq, max_freq) in enumerate(frequency_bands):
                spectrum[f"band_{min_freq}_{max_freq}Hz"] = 0.0

        return spectrum
